contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: f6176ec4-f42e-4212-8474-886c414ef571
    propagationLabels:
    - all
    toServerVersion: ""
id: Incident Response Playbook
inputs: []
name: Incident Response Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b122b277-0b46-4a28-89fe-0df641752f21
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: b122b277-0b46-4a28-89fe-0df641752f21
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      entryID: {}
      filePath: {}
      investigationID: {}
      text:
        simple: ${incident.labels.Artifact}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: b999a525-fb38-46d4-82ef-a9309de621a5
      iscommand: true
      name: Extract indicator from the alert
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: b999a525-fb38-46d4-82ef-a9309de621a5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    evidencedata:
      customfields: {}
      description:
        simple: Indicator Reputation
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
      - "11"
    note: true
    quietmode: 0
    scriptarguments:
      domain:
        complex:
          accessor: Artifact}
          root: ${incident.labels
      fullResponse: {}
      include_inactive: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: PassiveTotal
      description: Check domain reputation data
      id: 77f8d226-c299-4bcd-8485-ba622deae706
      iscommand: true
      name: Enrich indicator using RiskIQ's Passivetotal API
      script: PassiveTotal|||domain
      type: regular
      version: -1
    taskid: 77f8d226-c299-4bcd-8485-ba622deae706
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${DBotScore.Score}
          operator: isEqualString
          right:
            value:
              simple: "1"
      label: "yes"
    id: "3"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eda25508-0470-412f-81d1-c2955da26dad
      iscommand: false
      name: 'Is it a good indicator ? '
      type: condition
      version: -1
    taskid: eda25508-0470-412f-81d1-c2955da26dad
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      date_value: {}
      ref_name:
        simple: allowlist
      source: {}
      value:
        simple: ${Domain.Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Adds or updates a value in a reference set.
      id: 6f5c79cb-a823-422b-8fbc-1b02bea77cfd
      iscommand: true
      name: Add indicator to SIEM allow list
      script: '|||qradar-update-reference-set-value'
      type: regular
      version: -1
    taskid: 6f5c79cb-a823-422b-8fbc-1b02bea77cfd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      date_value: {}
      ref_name:
        simple: blocklist
      source: {}
      value:
        simple: ${Domain.Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Adds or updates a value in a reference set.
      id: 062ea2f4-e563-4bfa-8362-33a6dd072f82
      iscommand: true
      name: Add indicator to SIEM block list
      script: '|||qradar-update-reference-set-value'
      type: regular
      version: -1
    taskid: 062ea2f4-e563-4bfa-8362-33a6dd072f82
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "6":
    evidencedata:
      customfields: {}
      description:
        simple: Indicator in the SIEM list
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: true
    quietmode: 0
    scriptarguments:
      date_value: {}
      headers: {}
      ref_name:
        simple: allowlist
    separatecontext: false
    skipunavailable: false
    task:
      brand: QRadar
      description: Information about the reference set that had data added or updated.
        This returns information set but not the contained data. This feature is supported
        from version 8.1 and upward.
      id: e89b6b04-263f-4b2f-8dec-fafe8a4fe81c
      iscommand: true
      name: Print the indicator value in the SIEM allow list
      script: QRadar|||qradar-get-reference-by-name
      type: regular
      version: -1
    taskid: e89b6b04-263f-4b2f-8dec-fafe8a4fe81c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    evidencedata:
      customfields: {}
      description:
        simple: Indicator in the SIEM list
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: true
    quietmode: 0
    scriptarguments:
      date_value: {}
      headers: {}
      ref_name:
        simple: blocklist
    separatecontext: false
    skipunavailable: false
    task:
      brand: QRadar
      description: Information about the reference set that had data added or updated.
        This returns information set but not the contained data. This feature is supported
        from version 8.1 and upward.
      id: 3f67785e-5023-465e-8565-5fa5bbc702b2
      iscommand: true
      name: Print the indicator value in the SIEM blocklist
      script: QRadar|||qradar-get-reference-by-name
      type: regular
      version: -1
    taskid: 3f67785e-5023-465e-8565-5fa5bbc702b2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      name:
        simple: incident_response_report
      type:
        simple: pdf
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        A script to generate investigation summary report in an automated way
        Can be used in post-processing flow as well.
      id: dd03c228-cd8e-4f73-8cd0-1976c0191c61
      iscommand: false
      name: Generate report
      script: GenerateInvestigationSummaryReport
      type: regular
      version: -1
    taskid: dd03c228-cd8e-4f73-8cd0-1976c0191c61
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      additionalHeader: {}
      attachCIDs: {}
      attachIDs: {}
      attachNames: {}
      bcc: {}
      body: {}
      bodyType: {}
      cc: {}
      flag: {}
      from: {}
      headers: {}
      htmlBody: {}
      importance: {}
      raw_message: {}
      replyTo: {}
      subject: {}
      templateParams: {}
      to:
        simple: codepythongo@gmail.com
      transientFile: {}
      transientFileCID: {}
      transientFileContent: {}
      using:
        simple: Mail Sender (New)_instance_1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Mail Sender (New)
      description: Send an email
      id: ab40367f-373e-4e18-85c7-9af2d0aa0fd6
      iscommand: true
      name: Notify the team
      script: Mail Sender (New)|||send-mail
      type: regular
      version: -1
    taskid: ab40367f-373e-4e18-85c7-9af2d0aa0fd6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingconfirmationstatus: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 514731f0-1eb4-46eb-8aec-820e02f4060b
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 514731f0-1eb4-46eb-8aec-820e02f4060b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
  "11":
    evidencedata:
      customfields: {}
      description:
        simple: WhoIs info for the indicator
    fieldMapping:
    - incidentfield: WhoIsInfo
      output:
        simple: ${passivetotal.whois.email}
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: true
    quietmode: 0
    scriptarguments:
      compact_record: {}
      query:
        simple: ${Domain.Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: PassiveTotal
      description: Get WHOIS data for a domain or IP address
      id: 81f0efcc-04ab-4427-8c33-5a342259a4a8
      iscommand: true
      name: Get WhoIs info from Passivetotal
      script: PassiveTotal|||pt-whois
      type: regular
      version: -1
    taskid: 81f0efcc-04ab-4427-8c33-5a342259a4a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assignBy:
        simple: machine-learning
      email: {}
      onCall: {}
      roles: {}
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Assign analyst to incident.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
        current: The user that executed the command
      id: 0706b041-f544-4f54-845f-2d8026af22e2
      iscommand: false
      name: Use XSOAR ML to assign incident ownership
      script: AssignAnalystToIncident
      type: regular
      version: -1
    taskid: 0706b041-f544-4f54-845f-2d8026af22e2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1465,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
