contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: cc275775-5e01-4b1b-8fec-7e2474373ade
    propagationLabels:
    - all
    toServerVersion: ""
id: PROJX-LogRhythm Linking Job
inputs: []
name: PROJX-LogRhythm Linking Job
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a1398168-121b-4986-83ec-487f77ed19f7
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: a1398168-121b-4986-83ec-487f77ed19f7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 470,
          "y": 50
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    scriptarguments:
      execution-timeout:
        simple: "90000"
      inc_ids:
        simple: ${foundIncidents.id}
      inc_names:
        simple: ${foundIncidents.name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Links similar LR Alarms into a single Incident.
      id: 451dbaa9-00ef-4e42-8777-8ab5cf74e3c9
      iscommand: false
      name: Run the Linker Script
      script: cf9f8d43-6e31-4c41-8aa1-ace62d7c26cc
      type: regular
      version: -1
    taskid: 451dbaa9-00ef-4e42-8777-8ab5cf74e3c9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 205
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        complex:
          accessor: id
          root: incident
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 77bcf6b6-01fb-42ce-8248-5689a58096e8
      iscommand: true
      name: Job completed... Closing...
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 77bcf6b6-01fb-42ce-8248-5689a58096e8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 380,
        "x": 470,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
