contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: AWS GuardDuty | UnauthorizedAccess
inputs: []
name: AWS GuardDuty | UnauthorizedAccess
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b0fccb2d-0573-4cff-85c5-abc2675e04b4
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: b0fccb2d-0573-4cff-85c5-abc2675e04b4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 62af4347-bb90-48dd-8952-e3ad5394e0ce
      iscommand: false
      name: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      playbookId: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      type: playbook
      version: -1
      description: ''
    taskid: 62af4347-bb90-48dd-8952-e3ad5394e0ce
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: AWS Starter Pack
