contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: AWS GuardDuty | Policy
inputs: []
name: AWS GuardDuty | Policy
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3183a02e-221d-4b8f-802b-022559aca7f1
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 3183a02e-221d-4b8f-802b-022559aca7f1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 7b531604-14d6-4a7d-8a71-01c5ad0713b7
      iscommand: false
      name: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      playbookId: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      type: playbook
      version: -1
      description: ''
    taskid: 7b531604-14d6-4a7d-8a71-01c5ad0713b7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: AWS Starter Pack
