contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: d93eba71-70a0-4501-8130-404f0b79c4f2
    propagationLabels:
    - all
    toServerVersion: ""
id: AWS GuardDuty | Impact
inputs: []
name: AWS GuardDuty | Impact
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f32d79cf-b376-449a-8296-3213066e70c8
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: f32d79cf-b376-449a-8296-3213066e70c8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: c4e6d7aa-99d9-4e2f-8fdd-5e4928a88004
      iscommand: false
      name: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      playbookId: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      type: playbook
      version: -1
      description: ''
    taskid: c4e6d7aa-99d9-4e2f-8fdd-5e4928a88004
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: AWS Starter Pack