contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: AWS GuardDuty | Persistence
inputs: []
name: AWS GuardDuty | Persistence
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09d2c521-5c2a-4cdb-8066-357382fd9b19
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 09d2c521-5c2a-4cdb-8066-357382fd9b19
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: df655dd5-7bc9-4058-8390-297c1f4bcc5a
      iscommand: false
      name: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      playbookId: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      type: playbook
      version: -1
      description: ''
    taskid: df655dd5-7bc9-4058-8390-297c1f4bcc5a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: AWS Starter Pack
