contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: d93eba71-70a0-4501-8130-404f0b79c4f2
    propagationLabels:
    - all
    toServerVersion: ""
id: AWS GuardDuty | PenTest
inputs: []
name: AWS GuardDuty | PenTest
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 44b68ed5-4b19-4751-806d-8ab0216ace82
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 44b68ed5-4b19-4751-806d-8ab0216ace82
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 5372074a-928d-44d0-89e0-ea73504638ef
      iscommand: false
      name: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      playbookId: 213ecbf6-bf30-4ae5-89ff-9316eb1f4a90
      type: playbook
      version: -1
      description: ''
    taskid: 5372074a-928d-44d0-89e0-ea73504638ef
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: AWS Starter Pack