contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: d93eba71-70a0-4501-8130-404f0b79c4f2
    propagationLabels:
    - all
    toServerVersion: ""
id: AWS GuardDuty | Default
inputs: []
name: AWS GuardDuty | Default
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5b47ecfd-bf6a-4f00-841d-b116b59cf76b
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 5b47ecfd-bf6a-4f00-841d-b116b59cf76b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.resourcerole
          operator: isEqualString
          right:
            value:
              simple: ACTOR
      label: ACTOR
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.resourcerole
          operator: isEqualString
          right:
            value:
              simple: TARGET
      label: TARGET
    id: "1"
    ignoreworker: false
    nexttasks:
      ACTOR:
      - "2"
      TARGET:
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dcc75a80-c594-4335-8fe6-108ba4bebae1
      iscommand: false
      name: Actor or Target
      type: condition
      version: -1
    taskid: dcc75a80-c594-4335-8fe6-108ba4bebae1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
  "2":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: The AWS Resource is listed at the ACTOR - was remediation needed?
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: If so, what was done?
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: longText
      sender: ""
      title: Investigation for ACTOR
      totalanswers: 0
    id: "2"
    ignoreworker: false
    message:
      bcc:
      body: {}
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ${incident.productfields}
      id: 7e9061c0-eb60-43ab-80d3-6d5a327e88d7
      iscommand: false
      name: Manual Investigation for ACTOR
      type: collection
      version: -1
    taskid: 7e9061c0-eb60-43ab-80d3-6d5a327e88d7
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": -230,
          "y": 440
        }
      }
  "3":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: The AWS Resource is listed at the TARGET - was remediation needed?
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: If so, what was done?
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: longText
      sender: ""
      title: Investigation for TARGET
      totalanswers: 0
    id: "3"
    ignoreworker: false
    message:
      bcc:
      body: {}
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ${incident.productfields}
      id: 5f0e10ac-75d9-40a3-872a-9b6cf1acf957
      iscommand: false
      name: Manual Investigation for TARGET
      type: collection
      version: -1
    taskid: 5f0e10ac-75d9-40a3-872a-9b6cf1acf957
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 300,
          "y": 440
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 83a92908-b126-4323-8d4a-ec380bfa8524
      iscommand: false
      name: End
      type: title
      version: -1
      description: ''
    taskid: 83a92908-b126-4323-8d4a-ec380bfa8524
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 40,
          "y": 830
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 845,
        "width": 910,
        "x": -230,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
