contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: 662b7d12-4ec0-4f4b-8fe4-cf26bb384a9f
    propagationLabels:
    - all
    toServerVersion: ""
id: Remove Content Pack
inputs:
- description: ""
  key: package_id
  playbookInputQuery:
  required: true
  value: {}
name: Remove Content Pack
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e2dc0949-0f1a-4784-8974-2495e30c3ffa
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: e2dc0949-0f1a-4784-8974-2495e30c3ffa
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      package_id:
        simple: ${inputs.package_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: effeedb8-1590-4c86-8b62-54f467604c16
      iscommand: false
      name: Remove Content Pack
      script: eeab3401-4833-46d0-8ef5-78bb97fbc550
      type: regular
      version: -1
    taskid: effeedb8-1590-4c86-8b62-54f467604c16
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f51c76eb-c26c-409b-8c7e-051917b84e89
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: f51c76eb-c26c-409b-8c7e-051917b84e89
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
