contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: 96e32b7c-b720-4797-816b-802ad48395a5
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook fully automates the identification and remediation of emails
  sent to abuse inboxes by leveraging SlashNext’s patented behavioral phishing detection
  technology that uses millions of virtual browsers to detect unknown threats, return
  definitive verdicts, and forensics evidence of malicious phishing emails, at scale.
  Dramatically reduce the time and effort involved in researching suspicious URLs
  across digital sources with accurate, fully automated, and definitive URL analysis
  on demand. Abuse inbox management is often a manual and complex operation. With
  this playbook, teams can reduce up to 80% of the hours spent per week managing abuse
  inboxes, which also provides detection and remediation for Microsoft Office 365
  and similar secure email gateways.
id: SlashNext - Abuse Inbox Management
inputs: []
name: SlashNext - Abuse Inbox Management
outputs: []
rolename:
- Administrator
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f32d17d9-c4d9-4360-8dee-e3109a942049
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: f32d17d9-c4d9-4360-8dee-e3109a942049
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9a641d42-bb2b-43d9-8d96-1569a3523a39
      iscommand: false
      name: Running Abuse Inbox Playbook
      type: title
      version: -1
      description: ''
    taskid: 9a641d42-bb2b-43d9-8d96-1569a3523a39
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: f31adc93-9359-46d6-8733-2da68dca50ba
      iscommand: false
      name: 92e53b7e-cc3b-46da-84d9-b9ccbc133140
      playbookId: 92e53b7e-cc3b-46da-84d9-b9ccbc133140
      type: playbook
      version: -1
      description: ''
    taskid: f31adc93-9359-46d6-8733-2da68dca50ba
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 340
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
      - "11"
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d2f05ac6-4328-4537-8bce-fbfc60c7d753
      iscommand: false
      name: Search and Quarantine in Abuse Inbox
      type: title
      version: -1
      description: ''
    taskid: d2f05ac6-4328-4537-8bce-fbfc60c7d753
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1220,
          "y": 690
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      folder-path:
        simple: Inbox
      is-public: {}
      limit: {}
      message-id: {}
      query:
        simple: 'Body:(" slashnext.com Service. ") '
      selected-fields: {}
      target-mailbox: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS v2
      description: Searches for items in the specified mailbox. Specific permissions
        are needed for this operation to search in a target mailbox other than the
        default.
      id: 82f5b703-9779-48c9-8608-dc3cfc0201e7
      iscommand: true
      name: 'Search Emails with Malicious Domains '
      script: EWS v2|||ews-search-mailbox
      type: regular
      version: -1
    taskid: 82f5b703-9779-48c9-8608-dc3cfc0201e7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 800,
          "y": 830
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: SlashNext.Domain.Verdict
          operator: containsGeneral
          right:
            value:
              simple: Malicious
        - left:
            iscontext: true
            value:
              simple: SlashNext.IP.Verdict
          operator: containsGeneral
          right:
            value:
              simple: Malicious
        - left:
            iscontext: true
            value:
              simple: SlashNext.URL.Verdict
          operator: containsGeneral
          right:
            value:
              simple: Malicious
      label: "Yes"
    id: "6"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "14"
      "Yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fd8b4c86-1a52-4916-8f5c-8ae291cb4091
      iscommand: false
      name: Malicious Indicators Exist?
      type: condition
      version: -1
    taskid: fd8b4c86-1a52-4916-8f5c-8ae291cb4091
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 515
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: EWS.Items
          operator: isExists
      label: "Yes"
    id: "7"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "15"
      "Yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cd3c9f9a-0c20-4e6e-8b03-fea398423bf0
      iscommand: false
      name: Any Emails Found?
      type: condition
      version: -1
    taskid: cd3c9f9a-0c20-4e6e-8b03-fea398423bf0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1220,
          "y": 1000
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      is-public: {}
      item-id:
        simple: ${EWS.Items.itemId}
      target-folder-path:
        simple: Inbox/Phishing
      target-mailbox: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS v2
      description: Move an item to different folder in the mailbox.
      id: f8f887b5-77f9-4159-8c05-b8dae41ef249
      iscommand: true
      name: Move and Quarantine in Phishing Folder
      script: EWS v2|||ews-move-item
      type: regular
      version: -1
    taskid: f8f887b5-77f9-4159-8c05-b8dae41ef249
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1220,
          "y": 1190
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 1cde3a95-bf2b-4395-8a19-bc21c68b43b6
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 1cde3a95-bf2b-4395-8a19-bc21c68b43b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 800,
          "y": 1535
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      folder-path:
        simple: Inbox
      is-public: {}
      limit: {}
      message-id: {}
      query:
        complex:
          accessor: IP.Value}
          filters:
          - - left:
                iscontext: true
                value:
                  simple: SlashNext.IP.Verdict
              operator: isEqualString
              right:
                value:
                  simple: Malicious
          root: ${SlashNext
          transformers:
          - args:
              prefix:
                value:
                  simple: '"'
              suffix:
                value:
                  simple: '"'
            operator: concat
          - args:
              separator:
                value:
                  simple: ' OR '
            operator: join
          - args:
              prefix:
                value:
                  simple: Body:(
              suffix:
                value:
                  simple: )
            operator: concat
      selected-fields: {}
      target-mailbox: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS v2
      description: Searches for items in the specified mailbox. Specific permissions
        are needed for this operation to search in a target mailbox other than the
        default.
      id: d7ecde58-5a7b-4602-85a6-15dcd55b4e3c
      iscommand: true
      name: 'Search Emails with Malicious IPs '
      script: EWS v2|||ews-search-mailbox
      type: regular
      version: -1
    taskid: d7ecde58-5a7b-4602-85a6-15dcd55b4e3c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1220,
          "y": 830
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      folder-path:
        simple: Inbox
      is-public: {}
      limit: {}
      message-id: {}
      query:
        complex:
          accessor: URL.Value}
          filters:
          - - left:
                iscontext: true
                value:
                  simple: SlashNext.URL.Verdict
              operator: isEqualString
              right:
                value:
                  simple: Malicious
          root: ${SlashNext
          transformers:
          - args:
              prefix:
                value:
                  simple: '"'
              suffix:
                value:
                  simple: '"'
            operator: concat
          - args:
              separator:
                value:
                  simple: ' OR '
            operator: join
          - args:
              prefix:
                value:
                  simple: Body:(
              suffix:
                value:
                  simple: )
            operator: concat
      selected-fields: {}
      target-mailbox: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS v2
      description: Searches for items in the specified mailbox. Specific permissions
        are needed for this operation to search in a target mailbox other than the
        default.
      id: 045130ea-443f-4e8c-80e5-f979d38d52c3
      iscommand: true
      name: 'Search Emails with Malicious URLs '
      script: EWS v2|||ews-search-mailbox
      type: regular
      version: -1
    taskid: 045130ea-443f-4e8c-80e5-f979d38d52c3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1640,
          "y": 830
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      attachCIDs: {}
      attachIDs: {}
      attachNames: {}
      bcc: {}
      body: {}
      cc: {}
      htmlBody:
        simple: "<p style=\"color:black;\"><b>SlashNext Phishing Incident Response\
          \ - Malicious Email Detected</b></p> \n\n<p>Dear Abuse Inbox Admin,\n<br>\n\
          <br>\nThe following email has been detected to contain Malicious Indicators:\n\
          <br>\n<b>Subject: ${incident.labels.Email/subject}</b>\n</p>\n\n<p><br>Click\
          \ the link below to investigate the email and different indicators.</p>\n\
          <p>Evidence Board:</p>\n<a href=\"${demistoUrls.evidenceBoard}\">${demistoUrls.evidenceBoard}</a>\n\
          \n<p>All the emails that contain the same indicators have also also been\
          \ quarantined in the <b>Inbox -> Phishing</b> folder.</p>"
      replyTo: {}
      subject:
        simple: 'Abuse Inbox: Malicious Indicators Found in Reported Email'
      to:
        simple: ${incident.labels.Email}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS Mail Sender
      description: Sends an email using EWS.
      id: d98f90e7-81f1-4589-8a66-7cb4219c8729
      iscommand: true
      name: Send Malicious Quarantine Reporting Email
      script: EWS Mail Sender|||send-mail
      type: regular
      version: -1
    taskid: d98f90e7-81f1-4589-8a66-7cb4219c8729
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1220,
          "y": 1360
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      attachCIDs: {}
      attachIDs: {}
      attachNames: {}
      bcc: {}
      body: {}
      cc: {}
      htmlBody:
        simple: "<p style=\"color:black;\"><b>SlashNext Phishing Incident Response\
          \ - Malicious Email Detected</b></p> \n\n<p>Dear Abuse Inbox Admin,\n<br>\n\
          <br>\nThe following email does not contain any Malicious Indicators:\n<br>\n\
          <b>Subject: ${incident.labels.Email/subject}</b>\n</p>\n\n"
      replyTo: {}
      subject:
        simple: 'Abuse Inbox: No Malicious Indicators Found in Reported Email'
      to:
        simple: ${incident.labels.Email}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS Mail Sender
      description: Sends an email using EWS.
      id: 6eac9171-179e-468e-89a5-d84eb9f41a38
      iscommand: true
      name: Send No-Malicious Reporting Email
      script: EWS Mail Sender|||send-mail
      type: regular
      version: -1
    taskid: 6eac9171-179e-468e-89a5-d84eb9f41a38
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1360
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      attachCIDs: {}
      attachIDs: {}
      attachNames: {}
      bcc: {}
      body: {}
      cc: {}
      htmlBody:
        simple: "<p style=\"color:black;\"><b>SlashNext Phishing Incident Response\
          \ - Malicious Email Detected</b></p> \n\n<p>Dear Abuse Inbox Admin,\n<br>\n\
          <br>\nThe following email has been detected to contain Malicious Indicators:\n\
          <br>\n<b>Subject: ${incident.labels.Email/subject}</b>\n</p>\n\n<p><br>Click\
          \ the link below to investigate the email and different indicators.</p>\n\
          <p>Evidence Board:</p>\n<a href=\"${demistoUrls.evidenceBoard}\">${demistoUrls.evidenceBoard}</a>"
      replyTo: {}
      subject:
        simple: 'Abuse Inbox: Malicious Indicators Found in Reported Email'
      to:
        simple: ${incident.labels.Email}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS Mail Sender
      description: Sends an email using EWS.
      id: d9f10c28-7100-49aa-8e9b-fdf67778b604
      iscommand: true
      name: Send Malicious Reporting Email
      script: EWS Mail Sender|||send-mail
      type: regular
      version: -1
    taskid: d9f10c28-7100-49aa-8e9b-fdf67778b604
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 800,
          "y": 1360
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 70da2374-76ba-4b3a-8948-d99da9ba70ab
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 70da2374-76ba-4b3a-8948-d99da9ba70ab
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 800,
          "y": 1710
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "6_14_#default#": 0.85,
      "6_4_Yes": 0.55,
      "7_15_#default#": 0.82,
      "7_8_Yes": 0.36
    },
    "paper": {
      "dimensions": {
        "height": 1725,
        "width": 1642.5,
        "x": 377.5,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
