contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: 892f86c8-4680-419c-8e2b-8d9c7f60cdc0
    propagationLabels:
    - all
    toServerVersion: ""
description: After a secret is found in the GitHub repository, this playbook will
  require the XSOAR user to see if it is a real secret. Then, an email can be sent
  out to the commit author to remove the secret and respond.
id: GitHub Secrets Detection Playbook
inputs: []
name: GitHub Secrets Detection Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d8f599a3-1f15-4a01-84d4-213369099a10
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: d8f599a3-1f15-4a01-84d4-213369099a10
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    message:
      bcc:
      body: {}
      cc:
      format: ""
      methods: []
      replyOptions:
      - "Yes"
      - "No"
      subject:
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      "No":
      - "2"
      "Yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Please follow the GitHub link to the commit and check whether any potential secrets or secret files are being shared in the source code.

        ${incident.githubcommiturl}

        Are there any secrets leaked? If yes, please also disable this integration instance until the fix.
      id: 294759ec-a6ce-425f-8242-5824e85c7ec2
      iscommand: false
      name: Ask user to investigate on the commit
      type: condition
      version: -1
    taskid: 294759ec-a6ce-425f-8242-5824e85c7ec2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: No Secret was found
      closeReason:
        simple: False Positive
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: e7acd30e-d5c1-469c-8efc-f2cfe256f0c4
      iscommand: true
      name: Close investigation as a false positive
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e7acd30e-d5c1-469c-8efc-f2cfe256f0c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    message:
      bcc:
      body:
        simple: |-
          Hi ${incident.githubcommitauthorname},

          ${incident.details}

          Please remove the secrets from the commit history, and let us know by clicking the following link.
      cc:
      format: ""
      methods:
      - email
      replyOptions:
      - I have removed the secrets!
      subject:
        simple: 'GitHub Secrets detected: ${incident.githubcommiturl}'
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
        simple: ${incident.githubcommitauthoremail}
    nexttasks:
      I have removed the secrets!:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 87999f1c-5438-4298-8045-d7eb6f9e5d57
      iscommand: false
      name: Ask the commit author to remove the secrets
      type: condition
      version: -1
    taskid: 87999f1c-5438-4298-8045-d7eb6f9e5d57
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        If there are multiple secrets detected in this repository, there will be duplicated incidents created due to the rewritten commit history and a subsequent repository secrets rescan.

        Since this integration instance is disabled, it is advisable to fix all the secrets first and re-enable this integration instance.
      id: 27a82799-e7d6-4cac-8934-af321f8d2466
      iscommand: false
      name: Confirmation on the secrets removal
      type: regular
      version: -1
    taskid: 27a82799-e7d6-4cac-8934-af321f8d2466
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 07a4e60c-f323-4b00-8447-6567a522b4ea
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 07a4e60c-f323-4b00-8447-6567a522b4ea
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
