contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: FindSimilarIncidents
inputs:
- description: ""
  key: data
  playbookInputQuery:
  required: false
  value:
    simple: the data to find similar incidents on
name: FindSimilarIncidents
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2a126183-7992-48be-8b94-b2efca57de66
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 2a126183-7992-48be-8b94-b2efca57de66
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${inputs.data}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Lookup incidents with specified indicator. Use currentIncidentId
        to omit the existing incident from output
      id: 31332c60-7cc4-4367-889a-32b8e9b65f40
      iscommand: false
      name: Find Similar Incidents
      script: findIncidentsWithIndicator
      type: regular
      version: -1
    taskid: 31332c60-7cc4-4367-889a-32b8e9b65f40
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: 6.0.0
