contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: IPtoEndpointInfoViaXDR
inputs:
- description: ""
  key: IP
  playbookInputQuery:
  required: false
  value:
    simple: IP to look up via XDR
name: IPtoEndpointInfoViaXDR
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e559cb71-be3a-43d2-895d-f718e59ff28c
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: e559cb71-be3a-43d2-895d-f718e59ff28c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      alias_name: {}
      dist_name: {}
      endpoint_id_list: {}
      first_seen_gte: {}
      first_seen_lte: {}
      group_name: {}
      hostname: {}
      ip_list: {}
      isolate: {}
      last_seen_gte: {}
      last_seen_lte: {}
      limit: {}
      page: {}
      platform: {}
      sort_by: {}
      sort_order: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets a list of endpoints, according to the passed filters. If there
        are no filters it will return all endpoints. Filtering by multiple fields
        will be concatenated using AND condition (OR is not supported). Maximum result
        set size is 100. Offset is the zero-based number of endpoint from the start
        of the result set (start by counting from 0).
      id: cec51cba-7ee5-46c7-831b-6d3b0108aa7f
      iscommand: true
      name: IP to Endpoint Info via XDR
      script: '|||xdr-get-endpoints'
      type: regular
      version: -1
    taskid: cec51cba-7ee5-46c7-831b-6d3b0108aa7f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 235,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: 6.0.0
