contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: 'Scan hosts with Tenable.  This playbook scans hosts and creates an incident
  for each identified host with the Tenable IDs identified as well as their corresponding
  CVEs if any.  Checks are performed for existing vulnerability tickets within the
  system for a given host in order to perform deduplication of new scan results.  A
  monthly patch exclusion list can also be added to handled in band patching of systems
  that are currently on going. '
id: Tenable Network Scan
inputs:
- description: The Tenable Folder to list scans from
  key: FolderId
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.tenablefolder}
- description: ""
  key: ServiceNowGroup
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.servicenowgroups}
- description: ""
  key: hosts
  playbookInputQuery:
  required: false
  value:
    simple: the hosts to scan
name: Tenable Network Scan
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "74"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2401be13-c1b3-476e-8564-fc6c381fe081
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 2401be13-c1b3-476e-8564-fc6c381fe081
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": -595
        }
      }
  "20":
    id: "20"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "72"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8f9b92e4-11f5-49f9-8f76-3b69d368971f
      iscommand: false
      name: Gather Data From Tenable
      type: title
      version: -1
      description: ''
    taskid: 8f9b92e4-11f5-49f9-8f76-3b69d368971f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 60
        }
      }
  "64":
    id: "64"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "68"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 20eabc47-f3d5-4bd4-86b6-b68d696349aa
      iscommand: false
      name: DeDup/TicketCreation
      type: title
      version: -1
      description: ''
    taskid: 20eabc47-f3d5-4bd4-86b6-b68d696349aa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 765
        }
      }
  "67":
    id: "67"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      excludeList:
        simple: ${ExcludeList}
      hosts:
        simple: ${TenableSummary.HOST}
      incidentID:
        simple: ${incident.id}
      patchExclusion:
        simple: ${PatchExclude}
      vuln_summary:
        simple: ${TenableSummary.VULN}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2dacd248-c770-48fe-8ded-332c9dd8fe08
      iscommand: false
      name: Create Demisto Incidents
      script: 3dd4be56-6c17-420a-856d-ab2b127f410b
      type: regular
      version: -1
    taskid: 2dacd248-c770-48fe-8ded-332c9dd8fe08
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1275
        }
      }
  "68":
    id: "68"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "69"
    note: false
    quietmode: 0
    scriptarguments:
      vulns:
        simple: ${TenableSC.ScanResults.[0].Vulnerability}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 77019e71-0ebf-475f-82d9-65ad3b3e2364
      iscommand: false
      name: Group Hosts from Tenable Scan
      script: ed10af2b-c155-4077-8c59-32303cbd152b
      type: regular
      version: -1
    taskid: 77019e71-0ebf-475f-82d9-65ad3b3e2364
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 925
        }
      }
  "69":
    id: "69"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "67"
    note: false
    quietmode: 0
    scriptarguments:
      new_vulns: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6fe45b1d-abd0-4eb3-82ba-97ab76df5216
      iscommand: false
      name: Get Open Incidents
      script: 500a74f5-0ceb-4b6a-8f15-3c44bbf52e8d
      type: regular
      version: -1
    taskid: 6fe45b1d-abd0-4eb3-82ba-97ab76df5216
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1100
        }
      }
  "71":
    id: "71"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "64"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c447a925-7d99-476e-88da-1055bcb767ac
      iscommand: false
      name: Get Monthly Patch Exclusion List
      script: d847502a-e16d-4272-8fbf-497635d646cf
      type: regular
      version: -1
    taskid: c447a925-7d99-476e-88da-1055bcb767ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 575
        }
      }
  "72":
    id: "72"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "73"
    note: false
    quietmode: 0
    scriptarguments:
      scan_results_id:
        simple: ${TenableIO.Scan.Id}
      vulnerability_severity: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get a single report with Tenable.sc scan results
      id: 28cafbb2-cf5e-402d-8248-38549ac0755e
      iscommand: true
      name: Get Scan Report
      script: '|||tenable-sc-get-scan-report'
      type: regular
      version: -1
    taskid: 28cafbb2-cf5e-402d-8248-38549ac0755e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 190
        }
      }
  "73":
    id: "73"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "71"
    note: false
    quietmode: 0
    scriptarguments:
      limit: {}
      page: {}
      scan_results_id:
        simple: ${TenableSC.ScanResults.ID}
      vulnerability_id:
        simple: ${TenableSC.ScanResults.Vulnerability.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get details about a given vulnerability from a given Tenable.sc
        scan
      id: 30d07748-9f08-4ac0-801c-3371f8713def
      iscommand: true
      name: Get Tenable Vulnerability Details
      script: '|||tenable-sc-get-vulnerability'
      type: regular
      version: -1
    taskid: 30d07748-9f08-4ac0-801c-3371f8713def
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 380
        }
      }
  "74":
    id: "74"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "75"
    note: false
    quietmode: 0
    scriptarguments:
      folderId: {}
      lastModificationDate: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrive scans from the Tenable platform.
      id: 3457454e-8d4a-4f72-8d1d-49d10cc31dee
      iscommand: true
      name: List Tenable Scans
      script: '|||tenable-io-list-scans'
      type: regular
      version: -1
    taskid: 3457454e-8d4a-4f72-8d1d-49d10cc31dee
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": -450
        }
      }
  "75":
    form:
      description: The Tenable Scan List To run on host
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Which scan should be run
        options: []
        optionsarg:
        - simple: ${TenableIO.Scan.Name}
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: multiSelect
      sender: ""
      title: Scans
      totalanswers: 0
    id: "75"
    ignoreworker: false
    message:
      bcc:
      body:
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "76"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7bd52e65-6471-48a9-82de-6abbe75a43fc
      iscommand: false
      name: Which Scan should Run
      type: collection
      version: -1
    taskid: 7bd52e65-6471-48a9-82de-6abbe75a43fc
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 480,
          "y": -290
        }
      }
  "76":
    id: "76"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      scanId:
        complex:
          accessor: Id
          filters:
          - - left:
                iscontext: true
                value:
                  simple: TenableIO.Scan.Name
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: Scans.Answers.0
          root: TenableIO.Scan
      scanTargets:
        simple: ${inputs.host}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Lauch a scan with existing or custom targets. (You can specify
        custom targets in the arguements of this command.)
      id: 4664f2d5-caae-4c25-8f97-cd08211b08fc
      iscommand: true
      name: Lauch Tenable Scan
      script: '|||tenable-io-launch-scan'
      type: regular
      version: -1
    taskid: 4664f2d5-caae-4c25-8f97-cd08211b08fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": -110
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1965,
        "width": 380,
        "x": 480,
        "y": -595
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
