contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: TIM - Campaign correlation
inputs: []
name: TIM - Campaign correlation
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 67362123-ebf4-45f8-8eda-f6da6b272945
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 67362123-ebf4-45f8-8eda-f6da6b272945
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": -200,
          "y": -340
        }
      }
  "42":
    id: "42"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "44"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "no"
      index: {}
      key:
        simple: IncidentsWithIndicator
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: a2f7dc73-90d3-409a-8e5b-714aa1b70100
      iscommand: false
      name: Delete IncidentsWithIndicator key
      script: DeleteContext
      type: regular
      version: -1
    taskid: a2f7dc73-90d3-409a-8e5b-714aa1b70100
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -200,
          "y": -20
        }
      }
  "43":
    id: "43"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "47"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: unlink
      incidentId: {}
      linkedIncidentIDs:
        simple: ${incident.linkedIncidents}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: d44c341e-c8e8-4945-85dd-069a044a1430
      iscommand: true
      name: Unlink all incidents
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: d44c341e-c8e8-4945-85dd-069a044a1430
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -200,
          "y": 330
        }
      }
  "44":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${incident.linkedIncidents}
          operator: isNotEmpty
      label: "yes"
    id: "44"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "47"
      "yes":
      - "43"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b6b2dd76-1646-41ae-8036-771e31b5838f
      iscommand: false
      name: Are there any linked incidents?
      type: condition
      version: -1
    taskid: b6b2dd76-1646-41ae-8036-771e31b5838f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -200,
          "y": 150
        }
      }
  "45":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IncidentsWithIndicator}
          operator: isNotEmpty
      label: "yes"
    id: "45"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "44"
      "yes":
      - "42"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 507979a4-ee23-4a35-8498-9dab35f5e031
      iscommand: false
      name: Are there IncidentsWithIndicator values?
      type: condition
      version: -1
    taskid: 507979a4-ee23-4a35-8498-9dab35f5e031
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -200,
          "y": -180
        }
      }
  "46":
    id: "46"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "51"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${CVE.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Lookup incidents with specified indicator. Use currentIncidentId
        to omit the existing incident from output
      id: 98c63615-7c2a-48f2-82f0-2a5e7887180f
      iscommand: false
      name: Find Incidents with CVE's
      script: findIncidentsWithIndicator
      type: regular
      version: -1
    taskid: 98c63615-7c2a-48f2-82f0-2a5e7887180f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -900,
          "y": 630
        }
      }
  "47":
    id: "47"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "48"
      - "46"
      - "49"
      - "50"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 86e5d616-44b3-4b48-8d1b-97ed8e6b89e8
      iscommand: false
      name: Find and link based on CVE's and IOC's
      type: title
      version: -1
      description: ''
    taskid: 86e5d616-44b3-4b48-8d1b-97ed8e6b89e8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -200,
          "y": 490
        }
      }
  "48":
    id: "48"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "52"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${IP.Address}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Lookup incidents with specified indicator. Use currentIncidentId
        to omit the existing incident from output
      id: 83236e11-a456-4697-8076-0c23018e5093
      iscommand: false
      name: Find Incidents with IP's
      script: findIncidentsWithIndicator
      type: regular
      version: -1
    taskid: 83236e11-a456-4697-8076-0c23018e5093
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -450,
          "y": 630
        }
      }
  "49":
    id: "49"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "53"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Lookup incidents with specified indicator. Use currentIncidentId
        to omit the existing incident from output
      id: 11ab0a8c-1f6e-4425-8119-fc87584a1e5f
      iscommand: false
      name: Find Incidents with SHA256
      script: findIncidentsWithIndicator
      type: regular
      version: -1
    taskid: 11ab0a8c-1f6e-4425-8119-fc87584a1e5f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 630
        }
      }
  "50":
    id: "50"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "54"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${File.SHA1}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Lookup incidents with specified indicator. Use currentIncidentId
        to omit the existing incident from output
      id: 60ca2af3-9632-4f66-8a79-09eda78d9f64
      iscommand: false
      name: Find Incidents with SHA1
      script: findIncidentsWithIndicator
      type: regular
      version: -1
    taskid: 60ca2af3-9632-4f66-8a79-09eda78d9f64
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": 630
        }
      }
  "51":
    id: "51"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    scriptarguments:
      action: {}
      incidentId: {}
      linkedIncidentIDs:
        complex:
          accessor: incidentIDs}
          root: ${IncidentsWithIndicator
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: 3935a481-2e52-47f7-83f7-93d1aedbef2b
      iscommand: true
      name: Link incidents with CVE's
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: 3935a481-2e52-47f7-83f7-93d1aedbef2b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -900,
          "y": 800
        }
      }
  "52":
    id: "52"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    scriptarguments:
      action: {}
      incidentId: {}
      linkedIncidentIDs:
        complex:
          accessor: incidentIDs}
          root: ${IncidentsWithIndicator
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: 6b79b83d-cca4-4aca-8da7-b67892619235
      iscommand: true
      name: Link incidents with IP's
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: 6b79b83d-cca4-4aca-8da7-b67892619235
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -450,
          "y": 800
        }
      }
  "53":
    id: "53"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    scriptarguments:
      action: {}
      incidentId: {}
      linkedIncidentIDs:
        complex:
          accessor: incidentIDs}
          root: ${IncidentsWithIndicator
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: 97540500-7f1a-4e0a-8e35-fa01e16f94a2
      iscommand: true
      name: Link incidents with SHA256
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: 97540500-7f1a-4e0a-8e35-fa01e16f94a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 800
        }
      }
  "54":
    id: "54"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    scriptarguments:
      action: {}
      incidentId: {}
      linkedIncidentIDs:
        complex:
          accessor: incidentIDs}
          root: ${IncidentsWithIndicator
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: 9b0e6d62-2633-4555-84fc-05127553b2ae
      iscommand: true
      name: Link incidents with SHA1
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: 9b0e6d62-2633-4555-84fc-05127553b2ae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": 800
        }
      }
  "55":
    id: "55"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "56"
    note: false
    quietmode: 0
    scriptarguments:
      accountid: {}
      accountname: {}
      addLabels: {}
      agentid: {}
      app: {}
      appendMultiSelect: {}
      assetid: {}
      assignmentgroup: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      blockedaction: {}
      bugtraq: {}
      caller: {}
      city: {}
      closeNotes: {}
      closeReason: {}
      cloudservice: {}
      commandline: {}
      country: {}
      criticalassets: {}
      cs: {}
      customFields: {}
      customsev: {}
      cve: {}
      cvss: {}
      dbotMirrorDirection: {}
      dbotMirrorId: {}
      dbotMirrorInstance: {}
      dbotMirrorTags: {}
      dbotprediction: {}
      dbotpredictionprobability: {}
      dbottextsuggestionhighlighted: {}
      deleteEmptyField: {}
      dest: {}
      desthostname: {}
      destinationhostname: {}
      destinationip: {}
      destinationnetwork: {}
      destinationport: {}
      destip: {}
      destntdomain: {}
      destos: {}
      destsrc: {}
      details: {}
      detectedexternalhosts: {}
      detectedexternalips: {}
      detectedinternalhosts: {}
      detectedinternalips: {}
      detectedusers: {}
      detectionendtime: {}
      detectionid: {}
      detectionupdatetime: {}
      detectionurl: {}
      devicehash: {}
      devicename: {}
      duration: {}
      email: {}
      emailauthenticitycheck: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclassification: {}
      emailclientname: {}
      emailfrom: {}
      emailheaders: {}
      emailhtml: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      emailuserlist: {}
      employeedisplayname: {}
      employeeemail: {}
      employeemanageremail: {}
      escalation: {}
      eventid: {}
      eventtype: {}
      externaladdresses: {}
      filehash: {}
      filename: {}
      filepath: {}
      filesize: {}
      firstname: {}
      firstseen: {}
      helloworldid: {}
      helloworldstatus: {}
      helloworldtype: {}
      hostname: {}
      hostscore: {}
      hostscorehtml: {}
      id:
        simple: ${incident.linkedIncidents}
      infectedhosts: {}
      internaladdresses: {}
      internalhost: {}
      investigationstage: {}
      isolated: {}
      labels: {}
      lastmodifiedby: {}
      lastmodifiedon: {}
      lastname: {}
      lastseen: {}
      logsource: {}
      macaddress: {}
      maliciousbehavior: {}
      malwarefamily: {}
      mobiledevicemodel: {}
      name: {}
      occurred: {}
      opentenableids: {}
      os: {}
      osversion: {}
      owner: {}
      parentprocessid: {}
      phase: {}
      phishingsubtype: {}
      phonenumber: {}
      pid: {}
      policydeleted: {}
      policydescription: {}
      policydetails: {}
      policyid: {}
      policyrecommendation: {}
      policyremediable: {}
      policyseverity: {}
      policytype: {}
      prismacloudid: {}
      prismacloudreason: {}
      prismacloudrules: {}
      prismacloudstatus: {}
      prismacloudtime: {}
      protocol: {}
      protocols: {}
      quarantined: {}
      rating: {}
      region: {}
      regionid: {}
      replacePlaybook: {}
      reporteremailaddress: {}
      resourceapiname: {}
      resourcecloudtype: {}
      resourceid: {}
      resourcename: {}
      resourcetype: {}
      riskrating: {}
      riskscore: {}
      roles: {}
      rrn: {}
      samaccountname: {}
      scanlist: {}
      scanprotocol: {}
      scanservicecount: {}
      scanservices: {}
      scanstatssummary: {}
      scantime: {}
      scantype: {}
      sendemailbody: {}
      sendemailbutton: {}
      sendemailsubject: {}
      sendemailto: {}
      servicenowassignedto: {}
      servicenowassignmentgroup: {}
      servicenowcaller: {}
      servicenowcategory: {}
      servicenowcloseddate: {}
      servicenowdescription: {}
      servicenowduedate: {}
      servicenowescalation: {}
      servicenowimpact: {}
      servicenownotify: {}
      servicenowopeneddate: {}
      servicenowpriority: {}
      servicenowresolutionnotes: {}
      servicenowresolvedtime: {}
      servicenowseverity: {}
      servicenowstate: {}
      servicenowticketnumber: {}
      servicenowurgency: {}
      severity:
        simple: ${incident.severity}
      signature: {}
      skuname: {}
      skutier: {}
      sla: {}
      slaField: {}
      snowid: {}
      sourcehostname: {}
      sourceip: {}
      sourcenetwork: {}
      sourceport: {}
      sourceusername: {}
      src: {}
      srchostname: {}
      srcntdomain: {}
      srcos: {}
      srcuser: {}
      state: {}
      subcategory: {}
      subscriptionassignedby: {}
      subscriptioncreatedby: {}
      subscriptioncreatedon: {}
      subscriptiondescription: {}
      subscriptionid: {}
      subscriptionname: {}
      subscriptiontype: {}
      subscriptionupdatedby: {}
      subscriptionupdatedon: {}
      subtype: {}
      systemdefault: {}
      systems: {}
      targetfirewallversion: {}
      tenablecve: {}
      tenabledescription: {}
      tenablehost: {}
      tenableid: {}
      tenablemac: {}
      tenablemd: {}
      tenableports: {}
      tenablesolution: {}
      tenablesyn: {}
      tenablevulnerabilities: {}
      tenantname: {}
      terminatedaction: {}
      threatactor: {}
      threatalias: {}
      threatdetected: {}
      threatgoals: {}
      threatmotivation: {}
      ticketcloseddate: {}
      ticketnumber: {}
      ticketopeneddate: {}
      triggeredsecurityprofile: {}
      type: {}
      uniqueports: {}
      urlsslverification: {}
      user: {}
      useraccountcontrol: {}
      username: {}
      vendorid: {}
      vendorproduct: {}
      vpcid: {}
      vulnerabilitycategory: {}
      xdrassigned: {}
      xdrdetectiontime: {}
      xdrhostcount: {}
      xdrseverity: {}
      xdrurl: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: a5ba339e-af60-45ab-8a8e-788ad9733a8d
      iscommand: true
      name: Set Severity of all Linked Incidents to Campaign Severity
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: a5ba339e-af60-45ab-8a8e-788ad9733a8d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 760,
          "y": 1030
        }
      }
  "56":
    id: "56"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6a627e7b-1586-4e30-8f70-f739c5561d61
      iscommand: false
      name: Exit
      type: title
      version: -1
      description: ''
    taskid: 6a627e7b-1586-4e30-8f70-f739c5561d61
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 760,
          "y": 1190
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1595,
        "width": 2040,
        "x": -900,
        "y": -340
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: 6.0.0
