contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: Patch CVE - Manual
inputs: []
name: Patch CVE - Manual
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 26dd5c8d-1860-44b4-89b1-c563bb22e231
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 26dd5c8d-1860-44b4-89b1-c563bb22e231
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -20
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: patchmessage
      stringify: {}
      value:
        simple: Is  Patch for ${patchID} on ${incident.internalhost} Complete?
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 016ed621-aec0-4538-8700-bc4f8f0e8314
      iscommand: false
      name: Create Patch Message
      script: Set
      type: regular
      version: -1
    taskid: 016ed621-aec0-4538-8700-bc4f8f0e8314
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 140
        }
      }
  "2":
    form:
      description: Survey to confirm the patching status
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: ${patchmessage}
        options:
        - "Yes"
        - "No"
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: multiSelect
      sender: ""
      title: Patch Confirmation
      totalanswers: 0
    id: "2"
    ignoreworker: false
    message:
      bcc:
      body:
        simple: ${patchmessage}
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ea62c54b-130d-4898-82e1-cf73911ccf2e
      iscommand: false
      name: Ask to Confirm Patching
      type: collection
      version: -1
    taskid: ea62c54b-130d-4898-82e1-cf73911ccf2e
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 330
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Patch Confirmation.Answers.0
          operator: isEqualString
          right:
            value:
              simple: "Yes"
      label: "yes"
    id: "3"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 825b7669-9759-4f09-81da-881b6fbcd55d
      iscommand: false
      name: Is Patching Done?
      type: condition
      version: -1
    taskid: 825b7669-9759-4f09-81da-881b6fbcd55d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 510
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c548aaa1-e52a-46c8-8adf-e1855f439a2d
      iscommand: false
      name: Unassign indicator from incident
      type: regular
      version: -1
    taskid: c548aaa1-e52a-46c8-8adf-e1855f439a2d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 720,
          "y": 690
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 39c4db14-0c9c-4496-803d-8fb09d93ea36
      iscommand: false
      name: Update indicator as closed for parent ticket in demisto
      type: regular
      version: -1
    taskid: 39c4db14-0c9c-4496-803d-8fb09d93ea36
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 720,
          "y": 840
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: baff75a0-6309-42d2-8350-2799a8eae09e
      iscommand: false
      name: Make work note in service now that patch is done
      type: regular
      version: -1
    taskid: baff75a0-6309-42d2-8350-2799a8eae09e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 720,
          "y": 1000
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: Not Patched Yet
      closeReason:
        simple: Not Patched
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 8655f08c-e07a-41a2-8eda-652e76145adb
      iscommand: true
      name: Close Child
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8655f08c-e07a-41a2-8eda-652e76145adb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 1370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1485,
        "width": 680,
        "x": 420,
        "y": -20
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: 6.0.0
