contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: This playbook leverages the windows builtin Powershell and WinRM capabilities
  to connect to a Windows host to acquire and export the registry as a forensic evidence
  for further analysis. The capture can be for the entire registry or for a specific
  hive or path.
id: PS-Remote Get Registry
inputs:
- description: The host name for which to export the registry file. For example testpc01
  key: Host
  playbookInputQuery:
  required: false
  value: {}
- description: The registry hive/path to export, if no value is specified the entire
    registry will be exported.
  key: RegistryPath
  playbookInputQuery:
  required: false
  value:
    simple: all
- description: The path on the hostname on which to create the registry file. For
    example c:\registry.reg.
  key: FilePath
  playbookInputQuery:
  required: false
  value:
    simple: c:\full.reg
- description: Specify true to zip the reg file before sending it to XSOAR.
  key: ZipRegistry
  playbookInputQuery:
  required: false
  value:
    simple: "true"
name: PS-Remote Get Registry
outputs:
- contextPath: RegistryDetails
  description: The Registry file details.
  type: string
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 57f0c1b0-1f9e-4c8b-885a-e548a8c67381
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 57f0c1b0-1f9e-4c8b-885a-e548a8c67381
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 90
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isEqualString
          right:
            value:
              simple: PowerShell Remoting
      - - left:
            iscontext: true
            value:
              simple: modules.state
          operator: isEqualString
          right:
            value:
              simple: active
      label: "yes"
    id: "2"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d6775888-9ee4-4d5a-8fb8-7b63fea1d7a3
      iscommand: false
      name: Is PowerShell Remoting enabled?
      type: condition
      version: -1
      description: ''
    taskid: d6775888-9ee4-4d5a-8fb8-7b63fea1d7a3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 08556465-2825-4866-8690-cdf35c5115ab
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 08556465-2825-4866-8690-cdf35c5115ab
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2030
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Host
          operator: isNotEmpty
      label: "yes"
    id: "4"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3b998e71-a03c-4f32-89f3-1707c75c89b6
      iscommand: false
      name: Was a host specified?
      type: condition
      version: -1
      description: ''
    taskid: 3b998e71-a03c-4f32-89f3-1707c75c89b6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 220,
          "y": 430
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      file_path:
        simple: ${inputs.FilePath}
      host:
        simple: ${inputs.Host}
      reg_key_hive:
        simple: ${inputs.RegistryPath}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This command exports the specified Registry of hive to a file.
      id: 3664539d-b683-41e5-8f59-63bf0c98d8ee
      iscommand: true
      name: ps-remote-export-registry
      script: '|||ps-remote-export-registry'
      type: regular
      version: -1
    taskid: 3664539d-b683-41e5-8f59-63bf0c98d8ee
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 970
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      check_hash:
        simple: "true"
      host:
        simple: ${inputs.Host}
      ip: {}
      path:
        simple: ${inputs.FilePath}
      zip_file:
        simple: ${inputs.ZipRegistry}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Download a file from the remote endpoint.
      id: 0a858701-a43d-4a26-82d7-f370604400e5
      iscommand: true
      name: ps-remote-download-file
      script: '|||ps-remote-download-file'
      type: regular
      version: -1
    taskid: 0a858701-a43d-4a26-82d7-f370604400e5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 1330
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.FilePath
          operator: isNotEmpty
      label: "yes"
    id: "9"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bc816cf6-6e62-41e9-82aa-1be0f27057c3
      iscommand: false
      name: Was a registry file path specified?
      type: condition
      version: -1
      description: ''
    taskid: bc816cf6-6e62-41e9-82aa-1be0f27057c3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 110,
          "y": 680
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 75e629e9-3d8a-4efe-8c91-cea0828efe3d
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 75e629e9-3d8a-4efe-8c91-cea0828efe3d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 1160
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.ZipRegistry
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    id: "11"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: adef7f22-7280-4679-8eec-c2444dd323f2
      iscommand: false
      name: Was file zipped?
      type: condition
      version: -1
      description: ''
    taskid: adef7f22-7280-4679-8eec-c2444dd323f2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 40,
          "y": 1500
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isEqualString
              right:
                value:
                  simple: zip
          root: File
      fileName: {}
      lastZipFileInWarroom: {}
      password: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Unzip a file using fileName or entryID to specify a file. Unzipped
        files will be loaded to the War Room and names will be put into the context.
      id: 27a447af-898f-47ef-8198-e10652a99691
      iscommand: false
      name: Unzip file and mark as Evidence
      script: UnzipFile
      type: regular
      version: -1
    taskid: 27a447af-898f-47ef-8198-e10652a99691
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -190,
          "y": 1690
        }
      }
  "14":
    evidencedata:
      customfields: {}
      description:
        simple: A registry file acquired from a host
      tags:
        simple: Registry
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: RegistryDetails
      stringify: {}
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isEqualString
              right:
                value:
                  simple: reg
          root: File
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 8285e1f4-cf5b-4ca7-874f-21d9083b20c4
      iscommand: false
      name: Set registry file details
      script: Set
      type: regular
      version: -1
    taskid: 8285e1f4-cf5b-4ca7-874f-21d9083b20c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 1860
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2005,
        "width": 1020,
        "x": -190,
        "y": 90
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
