contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: 4c45ebf8-749a-4837-84a2-0be40c6459c2
    propagationLabels:
    - all
    toServerVersion: ""
description: Playbook inputs are set into the incident field 'details' by the Suspicious
  IOC Monitoring Job when IOC(s) hit(s) has(have) been found in ELK.
id: c98229ac-91e2-473c-894a-81e7a0d9e116
inputs: []
name: CORTEX-EMEA - TIM - Suspicious IOC Handling
outputs: []
sourceplaybookid: 8e517b31-439e-4550-88e5-ddf3bdce60ac
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "33"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6f8549fc-602f-417f-8563-6810f711fbbb
      iscommand: false
      name: ""
      version: -1
    taskid: 6f8549fc-602f-417f-8563-6810f711fbbb
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 65
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fd7fa1a7-9761-4b4c-87da-712aa9bf3897
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: fd7fa1a7-9761-4b4c-87da-712aa9bf3897
    timertriggers:
    - action: stop
      fieldname: remediationsla
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1915
        }
      }
  "22":
    defaultassigneecomplex:
      simple: ${incident.owner}
    id: "22"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7ac0ccfe-5cde-4094-8451-7aa02e9f738e
      iscommand: false
      name: Review SIEM hits & Analyze impact
      type: regular
      version: -1
    taskid: 7ac0ccfe-5cde-4094-8451-7aa02e9f738e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      assignBy:
        simple: random
      email: {}
      onCall: {}
      roles: {}
      username:
        simple: admin
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Assign analyst to incident.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
        current: The user that executed the command
      id: 00b9b043-db1c-4a33-8963-6060cf9b6baf
      iscommand: false
      name: Assign Analyst
      script: AssignAnalystToIncident
      type: regular
      version: -1
    taskid: 00b9b043-db1c-4a33-8963-6060cf9b6baf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "25":
    id: "25"
    ignoreworker: false
    message:
      bcc: null
      body:
        simple: Select indicators reputation update strategy
      cc: null
      format: ""
      methods: []
      replyOptions:
      - One by One (Manually)
      - Bulk update (Fully-automated)
      subject: null
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      Bulk update (Fully-automated):
      - "36"
      One by One (Manually):
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 60c8093a-b857-4288-8058-8f268a116089
      iscommand: false
      name: Select indicators reputation update strategy
      type: condition
      version: -1
    taskid: 60c8093a-b857-4288-8058-8f268a116089
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1215
        }
      }
  "26":
    defaultassigneecomplex:
      simple: ${incident.owner}
    id: "26"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 482b3249-e6a7-4f81-8f4d-6127b11f81fa
      iscommand: false
      name: Help yourself!
      type: regular
      version: -1
    taskid: 482b3249-e6a7-4f81-8f4d-6127b11f81fa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1740
        }
      }
  "28":
    formDisplay:
      bodybackgroundcolor: ""
      bodyfontcolor: ""
      headerbackgroundcolor: ""
      headerfontcolor: ""
      sender: ""
      submitbuttonbackgroundcolor: ""
      submitbuttonfontcolor: ""
      submittext: ""
    id: "28"
    ignoreworker: false
    message:
      bcc: null
      body:
        simple: What is the new reputation (Good or Bad)?
      cc: null
      format: ""
      methods: []
      replyOptions:
      - Good
      - Bad
      subject: null
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      Bad:
      - "46"
      Good:
      - "45"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 63b21bf3-38a9-4136-8fbc-c858c490ef99
      iscommand: false
      name: What is the new reputation (Good or Bad)?
      type: condition
      version: -1
    taskid: 63b21bf3-38a9-4136-8fbc-c858c490ef99
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1565
        }
      }
  "33":
    id: "33"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "43"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cf1773e7-be73-4262-88e1-c2b5e2f2c71e
      iscommand: false
      name: Analysis
      type: title
      version: -1
    taskid: cf1773e7-be73-4262-88e1-c2b5e2f2c71e
    timertriggers:
    - action: start
      fieldname: remediationsla
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 225
        }
      }
  "35":
    id: "35"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e66b57a6-47e2-4245-8459-9778d1f3d58a
      iscommand: false
      name: IOC Handling
      type: title
      version: -1
    taskid: e66b57a6-47e2-4245-8459-9778d1f3d58a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "36":
    id: "36"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IndicatorsWithElkHits=.
      fromdate: {}
      page: {}
      query:
        simple: tags:"SUSPICIOUS-IOC-ELK-HIT" AND investigationIDs:${incident.id}
      size: {}
      todate: {}
      value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.find.indicators
      id: 64b6b333-07d8-42b8-837e-9fe257f26c21
      iscommand: true
      name: Find tagged indicators (SUSPICIOUS-IOC-ELK-HIT)
      script: Builtin|||findIndicators
      type: regular
      version: -1
    taskid: 64b6b333-07d8-42b8-837e-9fe257f26c21
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1390
        }
      }
  "43":
    id: "43"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "44"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IndicatorsWithElkHits=.
      fromdate: {}
      page: {}
      query:
        complex:
          accessor: details
          root: incident
          transformers:
          - operator: trim
      size: {}
      todate: {}
      value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.find.indicators
      id: b94bfa31-f8b7-4146-8a95-6400ed5994e8
      iscommand: true
      name: Find Indicator Hits from incident details field that was set by the Suspicious
        IOC Monitoring Job
      script: Builtin|||findIndicators
      type: regular
      version: -1
    taskid: b94bfa31-f8b7-4146-8a95-6400ed5994e8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "44":
    id: "44"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      incidentId:
        complex:
          accessor: id
          root: incident
      indicatorsIDs: {}
      indicatorsValues:
        complex:
          accessor: value
          root: IndicatorsWithElkHits
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.associate.indicators
      id: 8b349ee7-4215-4b84-8c3e-3fc9cbe5965a
      iscommand: true
      name: Associate indicators found to the incident
      script: Builtin|||associateIndicatorsToIncident
      type: regular
      version: -1
    taskid: 8b349ee7-4215-4b84-8c3e-3fc9cbe5965a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "45":
    id: "45"
    ignoreworker: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        complex:
          root: IndicatorsWithElkHits
      reputation:
        simple: Good
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: b49f6aae-a023-46ca-87b6-8a1489fded09
      iscommand: false
      name: CORTEX-EMEA - TIM - Set Indicator Reputation (Good)
      playbookId: 631a6429-cd53-42da-8644-b649c4bef68a
      type: playbook
      version: -1
    taskid: b49f6aae-a023-46ca-87b6-8a1489fded09
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1740
        }
      }
  "46":
    id: "46"
    ignoreworker: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        complex:
          root: IndicatorsWithElkHits
      reputation:
        simple: Bad
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 141870af-5405-4bf7-8087-e1a8c5e1d1a4
      iscommand: false
      name: CORTEX-EMEA - TIM - Set Indicator Reputation (Bad)
      playbookId: 631a6429-cd53-42da-8644-b649c4bef68a
      type: playbook
      version: -1
    taskid: 141870af-5405-4bf7-8087-e1a8c5e1d1a4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1740
        }
      }
  "47":
    id: "47"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d3dcc5c1-9963-4fd2-83bd-fceea8df2886
      iscommand: false
      name: 'TODO: Close Incident - ITSM integration - Generate report - Make notes
        & evidences - Etc'
      type: title
      version: -1
    taskid: d3dcc5c1-9963-4fd2-83bd-fceea8df2886
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2080
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "25_26_One by One (Manually)": 0.25,
      "25_36_Bulk update (Fully-automated)": 0.74,
      "28_45_Good": 0.73
    },
    "paper": {
      "dimensions": {
        "height": 2080,
        "width": 1240,
        "x": 50,
        "y": 65
      }
    }
  }
