contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: GlobalProtect-Build-DNS-Host-Records
inputs: []
name: GlobalProtect-Build-DNS-Host-Records
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 60dab33c-5b56-4e48-8a89-d06b50a5c0e1
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 60dab33c-5b56-4e48-8a89-d06b50a5c0e1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets the current Global Protect Users
      id: 5a54924c-551a-4cf3-8e08-603367ce5bab
      iscommand: true
      name: List Connected GP Users
      script: '|||panos-get-current-users'
      type: regular
      version: -1
    taskid: 5a54924c-551a-4cf3-8e08-603367ce5bab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 515
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: defense.local
      host:
        complex:
          accessor: CurrentUsers.entry.computer}
          root: ${GlobalProtect
          transformers:
          - operator: toLowerCase
      ipadd:
        simple: ${GlobalProtect.CurrentUsers.entry.virtual-ip}
      status: {}
      view: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Infoblox_2.10.5
      description: Get Name info
      id: 713280b1-caa4-436a-86c9-4d603bcf6044
      iscommand: true
      name: Get Existing Host Record RefID
      script: Infoblox_2.10.5|||infoblox-get-refid
      type: regular
      version: -1
    taskid: 713280b1-caa4-436a-86c9-4d603bcf6044
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1040
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      host:
        simple: ${GlobalProtect.Hosts.Adds.name}
      ipadd:
        simple: ${GlobalProtect.Hosts.Adds.ipadd}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Infoblox_2.10.5
      description: Add a Host record to an empty IP
      id: 2c0ad509-4c93-4996-864c-a397d4abba24
      iscommand: true
      name: Create Host Record
      script: Infoblox_2.10.5|||infoblox-add-host-record
      type: regular
      version: -1
    taskid: 2c0ad509-4c93-4996-864c-a397d4abba24
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1535
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        complex:
          accessor: id
          root: incident
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: bf89b2e8-b3ae-4810-8e05-4b7a4b20f8b5
      iscommand: true
      name: Close Case
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: bf89b2e8-b3ae-4810-8e05-4b7a4b20f8b5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2205
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 92eba8b2-d731-40e2-88cb-be43f52172c3
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 92eba8b2-d731-40e2-88cb-be43f52172c3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2380
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      entryID: {}
      filePath: {}
      investigationID: {}
      text:
        simple: ${GlobalProtect.CurrentUsers.entry}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: ac8220bf-5337-4551-8571-88c85252c085
      iscommand: true
      name: Extract Data From Current GP Users
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: ac8220bf-5337-4551-8571-88c85252c085
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 690
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryID: {}
      filePath: {}
      investigationID: {}
      text:
        simple: ${incident.details}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 0ec89cdd-9f57-4b48-8395-3cfe0e2a9b7c
      iscommand: true
      name: Extract Indicators from Incident
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 0ec89cdd-9f57-4b48-8395-3cfe0e2a9b7c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      host:
        simple: ${GlobalProtect.Hosts.Updates.name}
      ipadd:
        simple: ${GlobalProtect.Hosts.Updates.ipadd}
      refid:
        simple: ${GlobalProtect.Hosts.Updates.refid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Infoblox_2.10.5
      description: Updates a host records IP address
      id: 2df79826-7d4b-4254-8e84-b308596f99eb
      iscommand: true
      name: Update Host Record
      script: Infoblox_2.10.5|||infoblox-update-host-record
      type: regular
      version: -1
    taskid: 2df79826-7d4b-4254-8e84-b308596f99eb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2030
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: GlobalProtect.Hosts
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: f7ec317f-0ca8-486f-8429-025b5df448db
      iscommand: false
      name: Remove RefId
      script: DeleteContext
      type: regular
      version: -1
    taskid: f7ec317f-0ca8-486f-8429-025b5df448db
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 865
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: GlobalProtect.Hosts.Updates
          operator: isExists
      label: "yes"
    id: "14"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5f5cfb7a-5eb0-47c5-8a2d-1b4809db7854
      iscommand: false
      name: Are There Hosts To Update?
      type: condition
      version: -1
    taskid: 5f5cfb7a-5eb0-47c5-8a2d-1b4809db7854
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1710
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: GlobalProtect.Hosts.Adds
          operator: isExists
      label: "yes"
    id: "15"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c678ecfb-ffc2-48f2-8622-31a6a0da5cc8
      iscommand: false
      name: Are There Hosts to Add?
      type: condition
      version: -1
    taskid: c678ecfb-ffc2-48f2-8622-31a6a0da5cc8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1215
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 68ea09bc-e14e-4733-81ce-ab0c6df51a22
      iscommand: false
      name: Update User Table
      type: title
      version: -1
      description: ''
    taskid: 68ea09bc-e14e-4733-81ce-ab0c6df51a22
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6b687963-e88e-46bd-84aa-bcfc3205e438
      iscommand: false
      name: Create DNS Record
      type: title
      version: -1
      description: ''
    taskid: 6b687963-e88e-46bd-84aa-bcfc3205e438
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: af279bba-ebd7-48b7-8da1-c7edbec03d2a
      iscommand: false
      name: Update DNS Record
      type: title
      version: -1
      description: ''
    taskid: af279bba-ebd7-48b7-8da1-c7edbec03d2a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1885
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2395,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: 6.0.0
