contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: Panorama - Update PAN-OS Policy from Kubernetes Network Policy
inputs:
- description: All Kubernetes network policies with this label will be picked up by
    the playbook.
  key: KubernetesPolicyLabel
  playbookInputQuery:
  required: true
  value:
    simple: PanoramaPolicy
- description: ""
  key: DeviceGroup
  playbookInputQuery:
  required: true
  value:
    simple: demisto
- description: ""
  key: ClusterName
  playbookInputQuery:
  required: true
  value:
    simple: gke_cps-containers-dev_us-central1-c_gunjan-cn-xsoar
- description: True if the playbook should automatically commit after pushing the
    policy changes, False otherwise. Default is False.
  key: AutoCommit
  playbookInputQuery:
  required: true
  value:
    simple: "False"
name: Panorama - Update PAN-OS Policy from Kubernetes Network Policy
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0a58beca-2997-45ee-8f85-83bc5a3be746
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 0a58beca-2997-45ee-8f85-83bc5a3be746
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": -135
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 04171c56-32b3-49cc-8704-56e07ba02180
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 04171c56-32b3-49cc-8704-56e07ba02180
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 2745
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
      - "29"
    note: false
    quietmode: 0
    scriptarguments:
      ClusterName:
        simple: ${inputs.ClusterName}
      KubernetesNetworkPolicy:
        simple: ${incident.details}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 60d9d2fc-6ad3-42d7-82e5-9d1553e1a593
      iscommand: false
      name: Derive PAN-OS objects from Kubernetes policy
      script: 732fe79e-48ac-4e61-ab3d-bb68323c7adc
      type: regular
      version: -1
    taskid: 60d9d2fc-6ad3-42d7-82e5-9d1553e1a593
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 360
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: allow
      application:
        simple: ${ConvertedPolicy.Rule.Application}
      category: {}
      description:
        simple: ${ConvertedPolicy.Rule.Description}
      destination:
        simple: ${ConvertedPolicy.Rule.Dst}
      destination_zone:
        simple: ${ConvertedPolicy.Rule.ToZone}
      device-group:
        simple: ${inputs.DeviceGroup}
      disable: {}
      log_forwarding: {}
      negate_destination: {}
      negate_source: {}
      pre_post:
        simple: post-rulebase
      rulename:
        simple: ${ConvertedPolicy.Rule.Name}
      service: {}
      source:
        simple: ${ConvertedPolicy.Rule.Src}
      source_user: {}
      source_zone:
        simple: ${ConvertedPolicy.Rule.FromZone}
      tags:
        simple: xsoar
      target: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Creates a policy rule.
      id: 23754f31-9708-4383-8f80-ebea0b74b2b4
      iscommand: true
      name: PAN-OS - Create rules
      script: '|||panorama-create-rule'
      type: regular
      version: -1
    taskid: 23754f31-9708-4383-8f80-ebea0b74b2b4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 2100
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 81e01ef7-3b82-41ba-8531-22f3f7a34353
      iscommand: false
      name: Analyze Network Policy
      type: title
      version: -1
      description: ''
    taskid: 81e01ef7-3b82-41ba-8531-22f3f7a34353
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 225
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.SecurityRule.Name
          operator: isEqualString
          right:
            iscontext: true
            value:
              simple: ${ConvertedPolicy.Rule.Name}
      label: "yes"
    id: "8"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1561f28e-6d28-4ded-8258-a68b0be4015a
      iscommand: false
      name: Does rule exist?
      type: condition
      version: -1
    taskid: 1561f28e-6d28-4ded-8258-a68b0be4015a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 857.5,
          "y": 1700
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.AutoCommit
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    id: "9"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c49ceaaf-353a-45b9-80dc-db4e334d6cd4
      iscommand: false
      name: Auto-Commit?
      type: condition
      version: -1
    taskid: c49ceaaf-353a-45b9-80dc-db4e334d6cd4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 2395
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Commit the PAN-OS Panorama or Firewall configuration.\nIf specified
        as Panorama, it also pushes the Policies to the specified Device Group in
        the instance.
      id: 3ef1993e-d3ed-4f28-8f98-d17623a1b46c
      iscommand: false
      name: PAN-OS Commit Configuration
      playbookId: PAN-OS Commit Configuration
      type: playbook
      version: -1
    taskid: 3ef1993e-d3ed-4f28-8f98-d17623a1b46c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 492.5,
          "y": 2570
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b13465d3-3446-4f09-8edb-b6a8e0a3eb9b
      iscommand: false
      name: Manual commit
      type: regular
      version: -1
    taskid: b13465d3-3446-4f09-8edb-b6a8e0a3eb9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 62.5,
          "y": 2570
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        complex:
          root: inputs.device-group
      dst: {}
      pre_post: {}
      rulename:
        simple: ${ConvertedPolicy.Rule.Name}
      where:
        simple: top
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Changes the location of a policy rule.
      id: 669f8270-bc92-4592-8c07-5ff0721032b7
      iscommand: true
      name: panorama-move-rule
      script: Panorama|||panorama-move-rule
      type: regular
      version: -1
    taskid: 669f8270-bc92-4592-8c07-5ff0721032b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 820,
          "y": 2230
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: aef16fca-24a9-4938-8ad2-3ed5ed8543cb
      iscommand: false
      name: Update OR delete
      type: regular
      version: -1
    taskid: aef16fca-24a9-4938-8ad2-3ed5ed8543cb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 1930
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        simple: ${inputs.DeviceGroup}
      pre_post:
        simple: post-rulebase
      tag: {}
      using:
        simple: Panorama-CN-Lior
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns a list of predefined Security Rules.
      id: 4e95169e-81ce-4a2d-8c8d-5420d8c4d1e3
      iscommand: true
      name: List rules in post rulebase
      script: '|||panorama-list-rules'
      type: regular
      version: -1
    taskid: 4e95169e-81ce-4a2d-8c8d-5420d8c4d1e3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 857.5,
          "y": 1525
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: 516e0b2a-554e-4ac6-889f-9321616f3adb
      iscommand: false
      name: delete  context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 516e0b2a-554e-4ac6-889f-9321616f3adb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 35
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        simple: ${inputs.DeviceGroup}
      tag: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns a list of address groups.
      id: ebdadd62-fa8e-46c2-8831-1a94cc9a8d35
      iscommand: true
      name: List existing DAGs
      script: '|||panorama-list-address-groups'
      type: regular
      version: -1
    taskid: ebdadd62-fa8e-46c2-8831-1a94cc9a8d35
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1370,
          "y": 940
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 39184869-204a-43ba-81fa-7a65813ce2b0
      iscommand: false
      name: DAG Creation
      type: title
      version: -1
      description: ''
    taskid: 39184869-204a-43ba-81fa-7a65813ce2b0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 392.5,
          "y": 545
        }
      }
  "21":
    id: "21"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ccae8dbc-41e6-4ea6-8905-7714d9a139b1
      iscommand: false
      name: Rule creation
      type: title
      version: -1
      description: ''
    taskid: ccae8dbc-41e6-4ea6-8905-7714d9a139b1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 1440
        }
      }
  "23":
    id: "23"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      addresses: {}
      description:
        simple: ${ConvertedPolicy.DAG.Description}
      device-group:
        simple: ${inputs.DeviceGroup}
      match:
        simple: ${ConvertedPolicy.DAG.Match}
      name:
        simple: ${ConvertedPolicy.DAG.Name}
      tags: {}
      type:
        simple: dynamic
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Creates a static or dynamic address group.
      id: be3ab9dc-f021-4eb6-8973-91060f98483d
      iscommand: true
      name: Create DAGs
      script: '|||panorama-create-address-group'
      type: regular
      version: -1
    taskid: be3ab9dc-f021-4eb6-8973-91060f98483d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1220
        }
      }
  "24":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: DAG
                root: ConvertedPolicy
          operator: isExists
      label: "yes"
    id: "24"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "21"
      "yes":
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4b4c2782-d8e3-496f-8cfc-d59ff2910fdc
      iscommand: false
      name: Any DAGs in the policy?
      type: condition
      version: -1
    taskid: 4b4c2782-d8e3-496f-8cfc-d59ff2910fdc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 670
        }
      }
  "26":
    id: "26"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 71f13900-19a2-4ac5-8adb-4daf81326028
      iscommand: false
      name: Create PAN-OS Dynamic Address Groups
      type: title
      version: -1
      description: ''
    taskid: 71f13900-19a2-4ac5-8adb-4daf81326028
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 880,
          "y": 860
        }
      }
  "27":
    id: "27"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 407a4eaa-77d8-4902-8165-e35eb9fccf9a
      iscommand: false
      name: Delete pre-existing DAGs that need to be recreated
      type: regular
      version: -1
    taskid: 407a4eaa-77d8-4902-8165-e35eb9fccf9a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1370,
          "y": 1080
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        simple: ${inputs.DeviceGroup}
      pre_post:
        simple: post-rulebase
      rulename:
        simple: ${ConvertedPolicy.Rule.Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Deletes a policy rule.
      id: 32b74add-714a-48aa-83fe-36c617ce03e4
      iscommand: true
      name: Delete rule
      script: Panorama|||panorama-delete-rule
      type: regular
      version: -1
    taskid: 32b74add-714a-48aa-83fe-36c617ce03e4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 1650
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5979a78e-fa9e-4751-826c-22247e920326
      iscommand: false
      name: Service Creation
      type: title
      version: -1
      description: ''
    taskid: 5979a78e-fa9e-4751-826c-22247e920326
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -120,
          "y": 545
        }
      }
  "30":
    id: "30"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      description: {}
      destination_port:
        complex:
          accessor: Port
          root: ConvertedPolicy.Services
          transformers:
          - operator: Stringify
      device-group:
        simple: ${inputs.DeviceGroup}
      name:
        complex:
          accessor: Name
          root: ConvertedPolicy.Services
      protocol:
        complex:
          accessor: Protocol
          root: ConvertedPolicy.Services
      source_port: {}
      tags: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Creates a service.
      id: 7c81e7c1-7da2-41ed-8786-731054b861fb
      iscommand: true
      name: Create Service Objects
      script: Panorama|||panorama-create-service
      type: regular
      version: -1
    taskid: 7c81e7c1-7da2-41ed-8786-731054b861fb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -110,
          "y": 660
        }
      }
  "31":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ConvertedPolicy.DAG.Name
          operator: isExists
      label: "yes"
    id: "31"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "21"
      "yes":
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2105a1dc-1638-4d38-843f-a25b087dfd64
      iscommand: false
      name: Any DAGs to create?
      type: condition
      version: -1
    taskid: 2105a1dc-1638-4d38-843f-a25b087dfd64
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1010
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "24_21_#default#": 0.32,
      "9_10_yes": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 2945,
        "width": 1870,
        "x": -120,
        "y": -135
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: 6.0.0
