contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: f31e67ff-ccf0-4801-87f1-4dc2e2749e82
    propagationLabels: []
    toServerVersion: ""
description: |+
  This playbook blocks malicious Indicators using all integrations that are enabled, using the following sub-playbooks:

  - Block URL - Generic
  - Block Account - Generic
  - Block IP - Generic v2
  - Block File - Generic v2

id: Block Indicators - Generic v3
inputs:
- description: The name of the IP blacklist Miner in  Minemeld.
  key: IPBlacklistMiner
  playbookInputQuery:
  required: false
  value: {}
- description: The name of the URL blacklist Miner in  Minemeld.
  key: URLBlacklistMiner
  playbookInputQuery:
  required: false
  value: {}
- description: Array of malicious IPs to block.
  key: IP
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: Indicator
      filters:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: ip
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: greaterThanOrEqual
          right:
            value:
              simple: "3"
      root: DBotScore
      transformers:
      - operator: uniq
- description: Array of malicious URLs to block.
  key: URL
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: Indicator
      filters:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: url
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: greaterThanOrEqual
          right:
            value:
              simple: "3"
      root: DBotScore
      transformers:
      - operator: uniq
- description: Array of malicious usernames to block.
  key: Username
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: Indicator
      filters:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: username
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: greaterThanOrEqual
          right:
            value:
              simple: "3"
      root: DBotScore
- description: The MD5 hash of the file you want to block.
  key: MD5
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: The SHA256 hash of the file you want to block.
  key: SHA256
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: |-
    This input determines whether Palo Alto Networks Panorama or Firewall Custom Block Rules are used.
    Specify True to use Custom Block Rules.
  key: CustomBlockRule
  playbookInputQuery:
  required: false
  value:
    simple: "True"
- description: Panorama log forwarding object name.
  key: LogForwarding
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    This input determines whether Palo Alto Networks Panorama or Firewall Static Address Groups are used.
    Specify the Static Address Group name for IP handling.
  key: AutoCommit
  playbookInputQuery:
  required: false
  value:
    simple: "No"
- description: |-
    This input determines whether Palo Alto Networks Panorama or Firewall External Dynamic Lists are used for blocking IPs.
    Specify the EDL name for IP handling.
  key: IPListName
  playbookInputQuery:
  required: false
  value:
    simple: Demisto-Remediation-IP-EDL
- description: |-
    This input determines whether Palo Alto Networks Panorama or Firewall External Dynamic Lists are used:
    * The IP address of the web server on which the files are stored.
    * The web server IP address is configured in the integration instance.
  key: EDLServerIP
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    This input determines whether Palo Alto Networks Panorama or Firewall Dynamic Address Groups are used.
    Specify the Dynamic Address Group tag name for IP handling.
  key: DAG
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    This input determines whether Palo Alto Networks Panorama or Firewall Static Address Groups are used.
    Specify the Static Address Group name for IP handling.
  key: StaticAddressGroup
  playbookInputQuery:
  required: false
  value: {}
- description: URL list from the instance context with which to override the remote
    file.
  key: URLListName
  playbookInputQuery:
  required: false
  value:
    simple: Demisto-Remediation-URL-EDL
- description: Custom URL Category name.
  key: CustomURLCategory
  playbookInputQuery:
  required: false
  value:
    simple: Demisto Remediation - Malicious URLs
- description: Custom URL category type. Insert "URL List"/ "Category Match".
  key: type
  playbookInputQuery:
  required: false
  value: {}
- description: Device group for the Custom URL Category (Panorama instances).
  key: device-group
  playbookInputQuery:
  required: false
  value: {}
- description: The list of categories. Relevant from PAN-OS v9.x.
  key: categories
  playbookInputQuery:
  required: false
  value: {}
name: Block Indicators - Generic v3
outputs:
- contextPath: CheckpointFWRule.Domain
  description: Rule domain.
- contextPath: CheckpointFWRule.Enabled
  description: Rule status.
- contextPath: CheckpointFWRule.Name
  description: Rule name.
- contextPath: CheckpointFWRule.UID
  description: Rule UID.
- contextPath: CheckpointFWRule.Type
  description: Rule Type.
- contextPath: CheckpointFWRule.DestinationNegate
  description: Rule destination negate status (True/False).
- contextPath: CheckpointFWRule.Action
  description: 'Rule action (Valid values are: Accept, Drop, Apply Layer, Ask, Info).'
- contextPath: CheckpointFWRule.Destination
  description: Rule Destination.
- contextPath: CheckpointFWRule.ActionSetting
  description: Rule action settings.
- contextPath: CheckpointFWRule.CustomFields
  description: Rule custom fields.
- contextPath: CheckpointFWRule.Data
  description: Rule data.
- contextPath: CheckpointFWRule.DataDirection
  description: Rule data direction.
- contextPath: CheckpointFWRule.DataNegate
  description: Rule data negate status (True/False).
- contextPath: CheckpointFWRule.Hits
  description: Rule hits count.
- contextPath: PanoramaRule.Direction
  description: Direction of the Panorama rule. Can be 'to','from', 'both'
  type: string
- contextPath: PanoramaRule.IP
  description: The IP the Panorama rule blocks
  type: string
- contextPath: PanoramaRule.Name
  description: Name of the Panorama rule
  type: string
- contextPath: CheckpointFWRule.Data.Name
  description: Rule data object name.
- contextPath: CheckpointFWRule.Data.Domain
  description: Information about the domain the data object belongs to.
- contextPath: CheckpointFWRule.Domain.Name
  description: Rule domain name.
- contextPath: CheckpointFWRule.Domain.UID
  description: Rule domain UID.
- contextPath: CheckpointFWRule.Domain.Type
  description: Rule domain type.
- contextPath: CheckpointFWRule.Hits.FirstDate
  description: The date of the first hit for the rule.
- contextPath: CheckpointFWRule.Hits.LastDate
  description: The date of the last hit for the rule.
- contextPath: CheckpointFWRule.Hits.Level
  description: Level of rule hits.
- contextPath: CheckpointFWRule.Hits.Percentage
  description: Percentage of rule hits
- contextPath: CheckpointFWRule.Hits.Value
  description: Value of rule hits.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d3ee8477-b8eb-4b83-88e8-1a3f5e4f26ca
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: d3ee8477-b8eb-4b83-88e8-1a3f5e4f26ca
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3ce0d3d2-cd32-467f-801d-8b6b43f5ce2a
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 3ce0d3d2-cd32-467f-801d-8b6b43f5ce2a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 515
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Tag: {}
      Username:
        complex:
          root: inputs.Username
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        This playbook blocks malicious usernames using all integrations that you have enabled.

        Supported integrations for this playbook:
        * Active Directory
        * PAN-OS - This requires PAN-OS 9.1 or higher.
      id: bd1529d5-9110-4c59-8757-77ec2be78cb7
      iscommand: false
      name: block_account_-_generic
      playbookId: block_account_-_generic
      type: playbook
      version: -1
    taskid: bd1529d5-9110-4c59-8757-77ec2be78cb7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 340
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
      - "9"
      - "12"
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76aa6efb-02f5-48ef-8136-ce462c1488e4
      iscommand: false
      name: Block indicators
      type: title
      version: -1
      description: ''
    taskid: 76aa6efb-02f5-48ef-8136-ce462c1488e4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      AutoCommit:
        complex:
          root: inputs.AutoCommit
      CustomBlockRule:
        complex:
          root: inputs.CustomBlockRule
      DAG:
        complex:
          root: inputs.DAG
      EDLServerIP:
        complex:
          root: inputs.EDLServerIP
      IP:
        complex:
          root: inputs.IP
      IPBlacklistMiner:
        complex:
          root: inputs.IPBlacklistMiner
      IPListName:
        complex:
          root: inputs.IPListName
      LogForwarding:
        complex:
          root: inputs.LogForwarding
      StaticAddressGroup:
        complex:
          root: inputs.StaticAddressGroup
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        This playbook blocks malicious IPs using all integrations that are enabled.

        Supported integrations for this playbook:
        * Check Point Firewall
        * Palo Alto Networks Minemeld
        * Palo Alto Networks PAN-OS
        * Zscaler
      id: 4c576d9c-c844-4005-8cbc-a48d4d7317b0
      iscommand: false
      name: Block IP - Generic v2
      playbookId: Block IP - Generic v2
      type: playbook
      version: -1
    taskid: 4c576d9c-c844-4005-8cbc-a48d4d7317b0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 340
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      AutoCommit:
        complex:
          root: inputs.AutoCommit
      CustomURLCategory:
        complex:
          root: inputs.CustomURLCategory
      EDLServerIP:
        complex:
          root: inputs.EDLServerIP
      LogForwarding:
        complex:
          root: inputs.LogForwarding
      URL:
        complex:
          accessor: blockedindicator
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: incident.blockedindicatortype
              operator: isEqualString
              right:
                value:
                  simple: URL
          root: incident
      URLBlacklistMiner:
        complex:
          root: inputs.URLBlacklistMiner
      URLListName:
        complex:
          root: inputs.URLListName
      categories:
        complex:
          root: inputs.categories
      device-group:
        complex:
          root: inputs.device-group
      type:
        complex:
          root: inputs.type
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        This playbook blocks malicious URLs using all integrations that are enabled.

        Supported integrations for this playbook:
        * Palo Alto Networks Minemeld
        * Palo Alto Networks PAN-OS
        * Zscaler
      id: c06dc607-4971-4705-856c-5bb0224ad649
      iscommand: false
      name: block_url_-_generic
      playbookId: block_url_-_generic
      type: playbook
      version: -1
    taskid: c06dc607-4971-4705-856c-5bb0224ad649
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 340
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      EventId: {}
      MD5:
        complex:
          accessor: MD5
          root: input
      SHA256:
        complex:
          accessor: SHA256
          root: input
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: de64712c-e137-4822-87b7-9c7df05656b8
      iscommand: false
      name: 9a341a6b-1335-4b43-8295-f2b61f912f7a
      playbookId: 9a341a6b-1335-4b43-8295-f2b61f912f7a
      type: playbook
      version: -1
      description: ''
    taskid: de64712c-e137-4822-87b7-9c7df05656b8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 340
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 530,
        "width": 1670,
        "x": 480,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
