contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: f31e67ff-ccf0-4801-87f1-4dc2e2749e82
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook accepts a SHA256 hash and adds the hash to the Global Quarantine
  list using the Cylance Protect v2 integration.
id: Block File - Cortex XDR
inputs:
- description: The SHA256 hash of the file to block.
  key: SHA256
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: SHA256
      filters:
      - - left:
            iscontext: true
            value:
              simple: File.Malicious
          operator: isExists
      root: File
      transformers:
      - operator: uniq
name: Block File - Cortex XDR
outputs:
- contextPath: CbResponse.BlockedHashes.LastBlock.Time
  description: Last block time
- contextPath: CbResponse.BlockedHashes.LastBlock.Hostname
  description: Last block hostname
- contextPath: CbResponse.BlockedHashes.LastBlock.CbSensorID
  description: Last block sensor ID
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5e4385e3-76c2-48e2-80a4-c3798cdae027
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 5e4385e3-76c2-48e2-80a4-c3798cdae027
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "6":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Cortex XDR - IR
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "6"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4ed149e0-5786-4320-8670-6c7593a464d5
      iscommand: false
      name: XDR Integrated?
      type: condition
      version: -1
    taskid: 4ed149e0-5786-4320-8670-6c7593a464d5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: blockedindicator
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: incident.blockedindicator
                    operator: stringHasLength
                    right:
                      value:
                        simple: "64"
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: incident.blockedindicatortype
                    operator: isEqualString
                    right:
                      value:
                        simple: File
                root: incident
          operator: isNotEmpty
      label: "yes"
    id: "8"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 86da2fc6-68eb-4b6b-8429-fa73e38ba0c0
      iscommand: false
      name: Is SHA256 exist?
      type: condition
      version: -1
    taskid: 86da2fc6-68eb-4b6b-8429-fa73e38ba0c0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 510,
          "y": 370
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2c14bf01-7fd9-45f8-8554-86d0c1332d81
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 2c14bf01-7fd9-45f8-8554-86d0c1332d81
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 710
        }
      }
  "10":
    continueonerror: true
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      comment:
        simple: Blocked by XSOAR
      hash_list:
        complex:
          accessor: blockedindicator
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Blacklists requested files which have not already been blacklisted
        or whitelisted.
      id: 0640873d-37f2-439a-83ce-6594fd374929
      iscommand: true
      name: Block File
      script: Cortex XDR - IR|||xdr-blacklist-files
      type: regular
      version: -1
    taskid: 0640873d-37f2-439a-83ce-6594fd374929
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 770,
          "y": 540
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "6_9_#default#": 0.64,
      "8_9_#default#": 0.32
    },
    "paper": {
      "dimensions": {
        "height": 725,
        "width": 885,
        "x": 265,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
