contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: f31e67ff-ccf0-4801-87f1-4dc2e2749e82
    propagationLabels:
    - all
    toServerVersion: ""
id: TIM Job
inputs: []
name: TIM Job
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 48bb2165-20ed-477f-8090-f32c6559dfe5
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 48bb2165-20ed-477f-8090-f32c6559dfe5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
