contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: Select App-ID Payload Results, Push to Firewall and Close Incident
inputs: []
name: Select App-ID Payload Results, Push to Firewall and Close Incident
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2b79622d-76bd-4356-8d47-e9ba6d63a21a
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 2b79622d-76bd-4356-8d47-e9ba6d63a21a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: 'Select Ascii Results:'
        options: []
        optionsarg:
        - simple: |-
            Ascii Result 1:
            ${incident.asciiresult1}
        - simple: |-
            Ascii Result 2:
            ${incident.asciiresult2}
        - simple: |-
            Ascii Result 3:
            ${incident.asciiresult3}
        - simple: |-
            Ascii Result 4:
            ${incident.asciiresult4}
        - simple: |-
            Ascii Result 5:
            ${incident.asciiresult5}
        - simple: |-
            Ascii Result 6:
            ${incident.asciiresult6}
        - simple: |-
            Ascii Result 7:
            ${incident.asciiresult7}
        - simple: |-
            Ascii Result 8:
            ${incident.asciiresult8}
        - simple: |-
            Ascii Result 9:
            ${incident.asciiresult9}
        - simple: |-
            Ascii Result 10:
            ${incident.asciiresult10}
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: multiSelect
      sender: ""
      title: 'Select Ascii Results:'
      totalanswers: 0
    id: "1"
    ignoreworker: false
    message:
      bcc:
      body:
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9253fc53-7582-4451-82d0-01efd039da9b
      iscommand: false
      name: Select Ascii Results
      type: collection
      version: -1
      description: ""
    taskid: 9253fc53-7582-4451-82d0-01efd039da9b
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 150,
          "y": 680
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: 53ff6947-903a-424c-81ce-2f594145fdea
      iscommand: false
      name: Clear Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 53ff6947-903a-424c-81ce-2f594145fdea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
  "3":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: 'Select Hex Results:'
        options: []
        optionsarg:
        - simple: |-
            Hex Result 1:
            ${incident.hexresult1}
        - simple: |-
            Hex Result 2:
            ${incident.hexresult2}
        - simple: |-
            Hex Result 3:
            ${incident.hexresult3}
        - simple: |-
            Hex Result 4:
            ${incident.hexresult4}
        - simple: |-
            Hex Result 5:
            ${incident.hexresult5}
        - simple: |-
            Hex Result 6:
            ${incident.hexresult6}
        - simple: |-
            Hex Result 7:
            ${incident.hexresult7}
        - simple: |-
            Hex Result 8:
            ${incident.hexresult8}
        - simple: |-
            Hex Result 9:
            ${incident.hexresult9}
        - simple: |-
            Hex Result 10:
            ${incident.hexresult10}
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: multiSelect
      sender: ""
      title: 'Select Hex Results:'
      totalanswers: 0
    id: "3"
    ignoreworker: false
    message:
      bcc:
      body:
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 610bcfde-dc2a-4d49-8f95-0e737ebaa373
      iscommand: false
      name: Select Hex Results
      type: collection
      version: -1
      description: ""
    taskid: 610bcfde-dc2a-4d49-8f95-0e737ebaa373
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 150,
          "y": 855
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 41f9c18f-df0a-4256-853e-d90e0c57b4c1
      iscommand: false
      name: Build Custom AppID
      script: c6273e6d-1f5e-4835-81f6-7688efae4c82
      type: regular
      version: -1
      description: ""
    taskid: 41f9c18f-df0a-4256-853e-d90e0c57b4c1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1020
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: set
      category: {}
      cmd: {}
      command: {}
      dst: {}
      element:
        simple: ${appidxml}
      from: {}
      job-id: {}
      key: {}
      log-type: {}
      pcap-id: {}
      period: {}
      query: {}
      reportname: {}
      reporttype: {}
      search-time: {}
      serialno: {}
      target: {}
      to: {}
      type:
        simple: config
      using:
        simple: VM700
      where: {}
      xpath:
        simple: ${appidxpath}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Run any command supported in the API.
      id: 276169c7-9d8e-4d2e-830a-2ed68f3e295a
      iscommand: true
      name: Push Change
      script: Panorama|||panorama
      type: regular
      version: -1
    taskid: 276169c7-9d8e-4d2e-830a-2ed68f3e295a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1170
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: VM700
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Commits a configuration to Palo Alto Firewall or Panorama, but
        does not validate if the commit was successful. Committing to Panorama does
        not push the configuration to the Firewalls. To push the configuration, run
        the panorama-push-to-device-group command.
      id: 25f563c7-44b8-47ce-8888-7baf4127da6e
      iscommand: true
      name: Commit Changes
      script: Panorama|||panorama-commit
      type: regular
      version: -1
    taskid: 25f563c7-44b8-47ce-8888-7baf4127da6e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1330
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      "No":
      - "13"
      "Yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5995b25c-4580-45f5-84da-8235323e632d
      iscommand: false
      name: Build AppID (Yes/No)
      type: condition
      version: -1
      description: ""
    taskid: 5995b25c-4580-45f5-84da-8235323e632d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 315
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2ef81f80-a602-4117-8121-49554f7d9c1b
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 2ef81f80-a602-4117-8121-49554f7d9c1b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 830,
          "y": 720
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: using
      AdditionalPollingCommandArgValues:
        simple: VM700
      Ids:
        complex:
          accessor: JobID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Panorama.Commit.Status
              operator: isEqualString
              right:
                value:
                  simple: Pending
          root: Panorama.Commit
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: job_id
      PollingCommandName:
        simple: panorama-commit-status
      Timeout:
        simple: "60"
      dt:
        simple: Panorama.Commit(val.Status != 'Completed' && val.Status != 'Failed').JobID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 8c204273-7860-4738-872a-9839af6a2abf
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 8c204273-7860-4738-872a-9839af6a2abf
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1490
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${Panorama.Commit.JobID}
      using:
        simple: VM700
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Returns commit status for a configuration.
      id: 08ae4757-2e01-43c9-8e4c-3b1ef632b7cb
      iscommand: true
      name: panorama-commit-status
      script: Panorama|||panorama-commit-status
      type: regular
      version: -1
    taskid: 08ae4757-2e01-43c9-8e4c-3b1ef632b7cb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1640
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.Commit.Status
          operator: isEqualString
          right:
            value:
              simple: Completed
      label: "yes"
    id: "11"
    ignoreworker: false
    nexttasks:
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c05666b6-799f-42e8-8736-0ff7ae454900
      iscommand: false
      name: Was Commit Successful
      type: condition
      version: -1
      description: ""
    taskid: c05666b6-799f-42e8-8736-0ff7ae454900
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1880
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: AppID created for ${incident.appidname}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingconfirmationstatus: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: e0f46eeb-681f-4b1e-8585-e4b48bd9243b
      iscommand: true
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e0f46eeb-681f-4b1e-8585-e4b48bd9243b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 820,
          "y": 1750
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: Admin declined AppID for ${incident.appidname}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingconfirmationstatus: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 327d5e2f-3e86-4239-8b80-96eb1ab0e316
      iscommand: true
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 327d5e2f-3e86-4239-8b80-96eb1ab0e316
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 830,
          "y": 520
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.appidname
          operator: match
          right:
            value:
              simple: \S+
      - - left:
            iscontext: true
            value:
              simple: incident.appidsignaturescope
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidsignaturename
          operator: match
          right:
            value:
              simple: \S+
      - - left:
            iscontext: true
            value:
              simple: incident.patternmatchcontext
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidcategory
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidsubcategory
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidtechnology
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidrisk
          operator: isNotEmpty
      label: "yes"
    id: "14"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "15"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b74e5e27-9444-4997-8310-280eb1de94ba
      iscommand: false
      name: Check for Required Fields
      type: condition
      version: -1
      description: ""
    taskid: b74e5e27-9444-4997-8310-280eb1de94ba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 150,
          "y": 520
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 23d753d9-7503-400e-87eb-a5bafbca4fda
      iscommand: false
      name: Please complete required fields
      type: title
      version: -1
      description: ''
    taskid: 23d753d9-7503-400e-87eb-a5bafbca4fda
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -360,
          "y": 460
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1925,
        "width": 1570,
        "x": -360,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: 6.0.0
