contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: Cyber Squatting detection
inputs: []
name: Cyber Squatting detection
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a3ef0bb1-6154-46fd-8644-f249ba03a342
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: a3ef0bb1-6154-46fd-8644-f249ba03a342
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
      - "8"
      - "9"
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: ${incident.details}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2e04d35b-bee5-4bdb-8367-0857a0a488e1
      iscommand: false
      name: Generate similar domain names for test
      script: 4b152684-f24b-4590-871e-58b7ee76e27c
      type: regular
      version: -1
    taskid: 2e04d35b-bee5-4bdb-8367-0857a0a488e1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      height: {}
      max_page_load_time: {}
      type: {}
      url:
        simple: ${Squatter.fuzzed_domains.domain}
      wait_time: {}
      width: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Converts the contents of a URL to an image file or a PDF file.
      id: 179393eb-7bbe-4544-8385-2da39f7bbcff
      iscommand: true
      name: Take screenshot
      script: '|||rasterize'
      type: regular
      version: -1
    taskid: 179393eb-7bbe-4544-8385-2da39f7bbcff
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 370
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      includeManual: {}
      includeSuspicious: {}
      maliciousQueryOverride: {}
      queryIndicators: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the investigation found any malicious indicators (file,
        URL, IP address, domain, or email). Returns "yes" if at least one malicious
        indicator is found.
      id: 7cd4a904-821a-4665-8f3c-f01007726771
      iscommand: false
      name: Malicious ?
      script: IsMaliciousIndicatorFound
      type: condition
      version: -1
    taskid: 7cd4a904-821a-4665-8f3c-f01007726771
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: 'Indicator value: ${Indicators.Value}, Indicator score ${Indicators.Score}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 8d17e404-443e-4dc1-828a-8a4380da8d79
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 8d17e404-443e-4dc1-828a-8a4380da8d79
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5a49123e-f1df-40c4-8b32-4bffcd07eae3
      iscommand: false
      name: Pass
      type: title
      version: -1
      description: ''
    taskid: 5a49123e-f1df-40c4-8b32-4bffcd07eae3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 735
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5218d328-5f40-44e0-8a3b-6a73a0eaeedd
      iscommand: false
      name: ToDo - How to compare images for similarity - ML?
      type: title
      version: -1
      description: ''
    taskid: 5218d328-5f40-44e0-8a3b-6a73a0eaeedd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 560
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      content:
        simple: '[''New domain registered'', ''Hosted as fake banking website'', ''Detected
          by security professionals'', ''First activity seen in our organization'']'
      header:
        simple: '[''12 Jan'', ''15 Jan'', ''25 Feb'', ''10 Mar'']'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 10c17d45-1701-4adf-8126-b98f5676de6e
      iscommand: false
      name: TimelineView
      script: b3763973-3ffd-492b-8c28-a96871d913bf
      type: regular
      version: -1
    taskid: 10c17d45-1701-4adf-8126-b98f5676de6e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      entryID: {}
      filePath: {}
      investigationID: {}
      text:
        simple: ${Squatter.fuzzed_domains.domain}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 254dfd24-3dae-4898-865b-dd37fd3dc2e4
      iscommand: true
      name: Extract Indicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 254dfd24-3dae-4898-865b-dd37fd3dc2e4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: domain
      query:
        simple: ${Squatter.fuzzed_domains.domain}
    separatecontext: false
    skipunavailable: false
    task:
      brand: PassiveTotal v2
      description: Gets WHOIS information records based on field matching queries.
      id: 033081fc-810a-4444-8506-7fe30a4ab61a
      iscommand: true
      name: Whois
      script: PassiveTotal v2|||pt-whois-search
      type: regular
      version: -1
    taskid: 033081fc-810a-4444-8506-7fe30a4ab61a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 370
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d7e6d062-8232-42a2-8c28-fb3956c02e27
      iscommand: false
      name: Domain age, hosting and other checks
      type: title
      version: -1
      description: ''
    taskid: d7e6d062-8232-42a2-8c28-fb3956c02e27
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 560
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "4_5_yes": 0.72
    },
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 1885,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: 6.0.0
