id: d9d715b7-2600-4535-8bfd-0978ff593976
version: 55
vcShouldKeepItemLegacyProdMachine: false
name: Test - ExtFilter
description: Test ExtFilter transformer
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e7c37eb4-69a2-4ad8-87f4-e125e9ff73a9
    type: start
    task:
      id: e7c37eb4-69a2-4ad8-87f4-e125e9ff73a9
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "13"
      - "14"
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 4478210f-e4d9-4b11-8615-6c51e984ffea
    type: regular
    task:
      id: 4478210f-e4d9-4b11-8615-6c51e984ffea
      version: -1
      name: Set Input Source
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      append: {}
      key:
        simple: Input
      stringify: {}
      value:
        complex:
          root: inputs.Input
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: dbbacd7f-0f9d-4414-8961-e32cb97c82c5
    type: regular
    task:
      id: dbbacd7f-0f9d-4414-8961-e32cb97c82c5
      version: -1
      name: Run ExtFilter
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      append: {}
      key:
        simple: Output
      stringify: {}
      value:
        complex:
          root: Input
          transformers:
          - operator: 257cf15c-c28a-4114-802f-1fff894c886c
            args:
              ctx_demisto:
                value:
                  simple: .
                iscontext: true
              ctx_incident:
                value:
                  simple: incident
                iscontext: true
              ctx_inputs:
                value:
                  simple: inputs
                iscontext: true
              ctx_lists:
                value:
                  simple: lists
                iscontext: true
              filter:
                value:
                  simple: ExtFilterFilter
                iscontext: true
              operation:
                value:
                  simple: inputs.ExtFilterOperation
                iscontext: true
              path:
                value:
                  simple: inputs.ExtFilterPath
                iscontext: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: e5ea1d43-7fde-4bd4-8747-a7fe41e78afc
    type: condition
    task:
      id: e5ea1d43-7fde-4bd4-8747-a7fe41e78afc
      version: -1
      name: Verify Result
      description: Prints text to war room (Markdown supported)
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: Output
                transformers:
                - operator: Stringify
            iscontext: true
          right:
            value:
              complex:
                root: ExpectedOutput
                transformers:
                - operator: Stringify
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 4203749f-44e9-4091-807c-303b131c8d2e
    type: title
    task:
      id: 4203749f-44e9-4091-807c-303b131c8d2e
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 8867eb64-a619-407c-8944-cdd344edb3a3
    type: regular
    task:
      id: 8867eb64-a619-407c-8944-cdd344edb3a3
      version: -1
      name: Set Expected Output
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      append: {}
      key:
        simple: ExpectedOutput
      stringify: {}
      value:
        complex:
          root: inputs.ExpectedOutput
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 887.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: b0e064ef-7f45-4889-8136-0e2ffe835d22
    type: regular
    task:
      id: b0e064ef-7f45-4889-8136-0e2ffe835d22
      version: -1
      name: Set ExtFilterFilter
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      append: {}
      key:
        simple: ExtFilterFilter
      stringify:
        simple: "true"
      value:
        complex:
          root: inputs.ExtFilterFilter
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: e1d9b996-ac38-48c1-8f34-596a561f8cfd
    type: regular
    task:
      id: e1d9b996-ac38-48c1-8f34-596a561f8cfd
      version: -1
      name: Parse ExtFilterFilter
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      append: {}
      key:
        simple: ExtFilterFilterObject
      stringify: {}
      value:
        complex:
          root: inputs.ExtFilterFilter
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -360,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 1627.5,
        "x": -360,
        "y": 50
      }
    }
  }
inputs:
- key: Input
  value: {}
  required: true
  description: Input Source
  playbookInputQuery: null
- key: ExtFilterPath
  value: {}
  required: false
  description: path for ExtFilter
  playbookInputQuery: null
- key: ExtFilterOperation
  value: {}
  required: true
  description: operation for ExtFilter
  playbookInputQuery: null
- key: ExtFilterFilter
  value: {}
  required: true
  description: filter for ExtFilter
  playbookInputQuery: null
- key: ExpectedOutput
  value: {}
  required: true
  description: Expected Output
  playbookInputQuery: null
outputs: []