id: d9d715b7-2600-4535-8bfd-0978ff593976
version: 57
vcShouldKeepItemLegacyProdMachine: false
name: Test - ExtFilter
description: Run ExtFilter for a test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3c681cc8-8dab-4ffd-8000-61fc881d3525
    type: start
    task:
      id: 3c681cc8-8dab-4ffd-8000-61fc881d3525
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "13"
      - "14"
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 9d0bd9f1-a193-41b4-8b67-63d64c28078e
    type: regular
    task:
      id: 9d0bd9f1-a193-41b4-8b67-63d64c28078e
      version: -1
      name: Set Input Source
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      append: {}
      key:
        simple: Input
      stringify: {}
      value:
        complex:
          root: inputs.Input
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: faca8871-03aa-44eb-8df2-8f7c8e6f6386
    type: regular
    task:
      id: faca8871-03aa-44eb-8df2-8f7c8e6f6386
      version: -1
      name: Run ExtFilter
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      append: {}
      key:
        simple: Output
      stringify: {}
      value:
        complex:
          root: Input
          transformers:
          - operator: 257cf15c-c28a-4114-802f-1fff894c886c
            args:
              ctx_demisto:
                value:
                  simple: .
                iscontext: true
              ctx_incident:
                value:
                  simple: incident
                iscontext: true
              ctx_inputs:
                value:
                  simple: inputs
                iscontext: true
              ctx_lists:
                value:
                  simple: lists
                iscontext: true
              filter:
                value:
                  simple: ExtFilterFilter
                iscontext: true
              operation:
                value:
                  simple: inputs.ExtFilterOperation
                iscontext: true
              path:
                value:
                  simple: inputs.ExtFilterPath
                iscontext: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 51c70733-40a9-4dc4-893e-caeaeb109f87
    type: condition
    task:
      id: 51c70733-40a9-4dc4-893e-caeaeb109f87
      version: -1
      name: Verify Result
      description: Prints text to war room (Markdown supported)
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: Output
                transformers:
                - operator: Stringify
            iscontext: true
          right:
            value:
              complex:
                root: ExpectedOutput
                transformers:
                - operator: Stringify
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: e44d9d92-2ef1-4185-8bf5-644c204fd908
    type: title
    task:
      id: e44d9d92-2ef1-4185-8bf5-644c204fd908
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 5ab39cc7-a765-4265-8958-e38ec4cfe1e9
    type: regular
    task:
      id: 5ab39cc7-a765-4265-8958-e38ec4cfe1e9
      version: -1
      name: Set Expected Output
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      append: {}
      key:
        simple: ExpectedOutput
      stringify: {}
      value:
        complex:
          root: inputs.ExpectedOutput
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 887.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 045da835-5545-4195-857f-5fa17c77d306
    type: regular
    task:
      id: 045da835-5545-4195-857f-5fa17c77d306
      version: -1
      name: Set ExtFilterFilter
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      append: {}
      key:
        simple: ExtFilterFilter
      stringify:
        simple: "true"
      value:
        complex:
          root: inputs.ExtFilterFilter
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 3a6375ee-0a8b-457e-8b51-03dd386beb97
    type: regular
    task:
      id: 3a6375ee-0a8b-457e-8b51-03dd386beb97
      version: -1
      name: Parse ExtFilterFilter
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      append: {}
      key:
        simple: ExtFilterFilterObject
      stringify: {}
      value:
        complex:
          root: inputs.ExtFilterFilter
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -360,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 1627.5,
        "x": -360,
        "y": 50
      }
    }
  }
inputs:
- key: Input
  value: {}
  required: true
  description: Input Source
  playbookInputQuery: null
- key: ExtFilterPath
  value: {}
  required: false
  description: path for ExtFilter
  playbookInputQuery: null
- key: ExtFilterOperation
  value: {}
  required: true
  description: operation for ExtFilter
  playbookInputQuery: null
- key: ExtFilterFilter
  value: {}
  required: true
  description: filter for ExtFilter
  playbookInputQuery: null
- key: ExpectedOutput
  value: {}
  required: true
  description: Expected Output
  playbookInputQuery: null
outputs: []
