contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: 'This Playbook is designed to automate  response actions to suspicious
  bitcoin mining activity detected and reported by AWS Security hub. '
id: IR Playbook AWS Security Hub
inputs: []
name: IR Playbook AWS Security Hub
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 168d2bfb-824a-4798-8ea0-7b4764912f4e
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 168d2bfb-824a-4798-8ea0-7b4764912f4e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
      - "7"
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: RedLock
      id: ae93621f-1e3f-4029-8dfe-4c5da888ad9b
      iscommand: false
      name: Print and Mark the Alert as Evidence
      script: Print
      type: regular
      version: -1
    taskid: ae93621f-1e3f-4029-8dfe-4c5da888ad9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      filters: {}
      instanceIds:
        simple: i-055c15ff60b155811
      region: {}
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: AWS - EC2_copy
      description: Describes one or more of your instances.
      id: 5219648b-75be-4b5d-86a7-bc1a325ff81c
      iscommand: true
      name: Get Instance Details
      script: AWS - EC2_copy|||aws-ec2-describe-instances
      type: regular
      version: -1
    taskid: 5219648b-75be-4b5d-86a7-bc1a325ff81c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 545
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      filters: {}
      groupIds:
        simple: ${AWS.EC2.Instances.SecurityGroups.GroupId}
      groupNames: {}
      region: {}
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: AWS - EC2_copy
      description: Describes one or more of your security groups.
      id: df0f364d-d364-40ec-8b2b-8c24330deed4
      iscommand: true
      name: Get Security Group Details
      script: AWS - EC2_copy|||aws-ec2-describe-security-groups
      type: regular
      version: -1
    taskid: df0f364d-d364-40ec-8b2b-8c24330deed4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 720
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 86f48b2f-dbf2-494b-869c-ca9afb93448f
      iscommand: false
      name: Quarantine the infected  Instances
      type: title
      version: -1
      description: ''
    taskid: 86f48b2f-dbf2-494b-869c-ca9afb93448f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 705,
          "y": 385
        }
      }
  "7":
    continueonerror: true
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assignee: {}
      description:
        simple: 'AWS alert Information for suspected Cryptocurrency mining activity '
      dueDate: {}
      issueJson: {}
      issueTypeId: {}
      issueTypeName: {}
      labels: {}
      parentIssueId: {}
      parentIssueKey: {}
      priority: {}
      projectKey: {}
      projectName: {}
      reporter: {}
      summary:
        simple: ${incident.details}
    separatecontext: false
    skipunavailable: false
    task:
      brand: jira
      id: 4cb20240-4644-4016-8a4f-ce94ea5479da
      iscommand: true
      name: Open JIRA ticket for Cryptocurrency Mining Alert
      script: jira|||jira-create-issue
      type: regular
      version: -1
    taskid: 4cb20240-4644-4016-8a4f-ce94ea5479da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -330,
          "y": 385
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      assignee: {}
      description: {}
      dueDate: {}
      issueJson: {}
      issueTypeId: {}
      issueTypeName: {}
      labels: {}
      priority: {}
      projectKey: {}
      projectName: {}
      reporter: {}
      summary:
        simple: P-87
    separatecontext: false
    skipunavailable: false
    task:
      brand: jira
      id: 0569ab2e-c265-474c-8d6e-66c15106855c
      iscommand: true
      name: Update the JIRA ticket
      script: jira|||jira-create-issue
      type: regular
      version: -1
    taskid: 0569ab2e-c265-474c-8d6e-66c15106855c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1770
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      awsinstancename: {}
      closeNotes: {}
      closeReason: {}
      disposition: {}
      id:
        simple: ${incident.id}
      internalemail: {}
      killchain: {}
      lob: {}
      shiftnotes: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      id: ac4491b8-4dfd-4c93-8b34-191c3e6c0f04
      iscommand: true
      name: Close the Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: ac4491b8-4dfd-4c93-8b34-191c3e6c0f04
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1945
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 9aee0e72-fdaa-421b-8a45-d69b10cf7b4e
      iscommand: false
      name: extract_indicators_-_generic
      playbookId: extract_indicators_-_generic
      type: playbook
      version: -1
      description: ''
    taskid: 9aee0e72-fdaa-421b-8a45-d69b10cf7b4e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 4faf4d1c-ae36-4469-809d-19d414ed5b6e
      iscommand: false
      name: entity_enrichment_generic
      playbookId: entity_enrichment_generic
      type: playbook
      version: -1
      description: ''
    taskid: 4faf4d1c-ae36-4469-809d-19d414ed5b6e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 86f924b3-583a-4553-8fbd-56c1eda22a64
      iscommand: false
      name: Handle Indicator Stuff
      type: title
      version: -1
      description: ''
    taskid: 86f924b3-583a-4553-8fbd-56c1eda22a64
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 910
        }
      }
  "13":
    continueonerror: true
    id: "13"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4d75f03b-30dd-47b0-8ef4-2289c26bce46
      iscommand: false
      name: 'Malicious Indicators Found ? '
      script: IsMaliciousIndicatorFound
      type: condition
      version: -1
    taskid: 4d75f03b-30dd-47b0-8ef4-2289c26bce46
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "14":
    continueonerror: true
    id: "14"
    ignoreworker: false
    nexttasks:
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      left:
        simple: P-87
      right:
        simple: P-87
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6008c8e7-7097-4895-8bc0-56ed92f95064
      iscommand: false
      name: 'If Malicious IPs Found ? '
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: 6008c8e7-7097-4895-8bc0-56ed92f95064
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
  "15":
    continueonerror: true
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      direction:
        simple: both
      ip:
        simple: 60.191.38.77
      ipname: {}
      rulename:
        simple: P-87
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c6f6ee4-c6c2-4174-8def-d7fcac8defa1
      iscommand: false
      name: Block Malicious IPs
      script: BlockIP
      type: regular
      version: -1
    taskid: 9c6f6ee4-c6c2-4174-8def-d7fcac8defa1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      attachIDs: {}
      bcc:
        simple: pramukh@demisto.com
      body:
        simple: ${incident.awsgdfindingtype}
      cc: {}
      htmlBody: {}
      noteEntryID: {}
      replyTo: {}
      subject:
        simple: "Instance has been quarantined for the Cryptocurrency mining alert\
          \ \n ${incident.awsgdfindingtype}"
      to:
        simple: art@demisto.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b7c8581c-f158-4a37-8a11-77657dedd7da
      iscommand: false
      name: Send Email to Analyst
      script: SendEmail
      type: regular
      version: -1
    taskid: b7c8581c-f158-4a37-8a11-77657dedd7da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 1420
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6f62f8fd-cae8-4b73-8f50-c24e112431a7
      iscommand: false
      name: Analyst Review - Wait for Response
      type: regular
      version: -1
    taskid: 6f62f8fd-cae8-4b73-8f50-c24e112431a7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      attachmentId: {}
      deleteOnTermination: {}
      description: {}
      groups:
        simple: ${AWS.EC2.SecurityGroups.GroupId}
      networkInterfaceId:
        complex:
          accessor: EC2.Instances.NetworkInterfaces.NetworkInterfaceId}
          root: ${AWS
      region: {}
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
      sourceDestCheck: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: AWS - EC2_copy
      id: 20ba51d1-82fc-4785-87ed-591c8882d6f3
      iscommand: true
      name: Change Network Interface Security Group to Demisto Isolation SG
      script: AWS - EC2_copy|||aws-ec2-modify-network-interface-attribute
      type: regular
      version: -1
    taskid: 20ba51d1-82fc-4785-87ed-591c8882d6f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1990,
        "width": 1415,
        "x": -330,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
